#!/usr/bin/env python3
"""Generate the per-good price readings this mod is built on.

For every good the game charges construction in, emit a script value giving that
good's construction cost impact in the country's own market, as a percentage:

    bgt_impact_lumber   -33.0  lumber is as cheap as the engine will credit
                          0.0  lumber sits at its default price
                        +12.5  lumber is dear and construction costs more

The formula is not ours. It is Glorp UI's `glorpui_construction_good_adjustment`,
which Construction Manager uses for its own minimum-discount gates, so the number
this mod shows and the number CM gates on cannot drift apart. Written out per
good rather than called, because that value expects `scope:cm_location` and this
mod asks the question of a country.

The list of goods is read from Construction Manager, not typed here: its
`cm_construction_demand_<good>` maps are the game's construction goods, and if a
patch adds one, this picks it up on the next run.

    python3 mods/goods_target/tools/generate.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(REPO / "tools"))

import eu5data  # noqa: E402
import refs  # noqa: E402

OUT = MOD / "in_game/common/script_values/bgt_generated_values.txt"

CM_COSTS = "in_game/common/script_values/cm_construction_cost_adjustments_script_values.txt"
DEMAND_MAP = re.compile(r"cm_construction_demand_([a-z_]+)")
# The subset CM calls "standard": the goods a player can actually depress by
# building more of them. The rest — gold, tools, paper — do not respond.
STANDARD = ("lumber", "masonry", "glass", "sand", "stone")

HEADER = """\
# Generated by mods/goods_target/tools/generate.py. Do not edit by hand.
#
# One value per construction good: what that good's market price is doing to the
# cost of building things, as a percentage. Negative is a discount. The engine
# credits at most -33% (define:NMarket|MIN_PRICE_IMPACT) once every input is
# weighted, and a single good reaches that only when it is the whole recipe.
#
# Root is the country. The market read is the capital's.
"""

VALUE = """\
bgt_impact_%(good)s = {
\tgoods:%(good)s = { save_temporary_scope_as = bgt_good }
\tif = {
\t\tlimit = { "capital.market.market_price(scope:bgt_good)" > "default_price(scope:bgt_good)" }
\t\tvalue = "capital.market.market_price(scope:bgt_good)"
\t\tdivide = "default_price(scope:bgt_good)"
\t\tsubtract = 1
\t\tdivide = 2
\t}
\telse_if = {
\t\tlimit = { "capital.market.market_price(scope:bgt_good)" < "default_price(scope:bgt_good)" }
\t\tvalue = "capital.market.market_price(scope:bgt_good)"
\t\tdivide = "default_price(scope:bgt_good)"
\t\tsubtract = 1
\t\tmultiply = {
\t\t\tvalue = 1
\t\t\tdivide = 9
\t\t\tadd = 1
\t\t}
\t}
\telse = { value = 0 }
\tmultiply = 100
\tmin = -33
\tmax = 300
}
"""


def construction_goods() -> list[str]:
    """The goods the game charges construction in, per Construction Manager."""
    path = refs.known("construction_manager") / CM_COSTS
    if not path.is_file():
        raise SystemExit(f"no construction cost values at {path}")
    found = sorted(set(DEMAND_MAP.findall(path.read_text(encoding="utf-8-sig"))))
    if not found:
        raise SystemExit(f"no cm_construction_demand_<good> maps in {path.name}")
    return found


def main() -> int:
    goods = construction_goods()
    catalogue = eu5data.load_game().all_goods

    unknown = [g for g in goods if g not in catalogue]
    if unknown:
        # CM names goods_gold where the catalogue says gold; anything else here
        # means a patch renamed a good and this mod would emit a dead value.
        print("not in the goods catalogue, skipped: %s" % ", ".join(unknown),
              file=sys.stderr)
        goods = [g for g in goods if g in catalogue]

    missing = [g for g in STANDARD if g not in goods]
    if missing:
        raise SystemExit("CM no longer charges construction in %s — the standard "
                         "goods this mod is about have moved" % ", ".join(missing))

    body = [HEADER]
    for good in goods:
        body.append(VALUE % {"good": good})

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("﻿" + "\n".join(body), encoding="utf-8")
    print("wrote %s" % OUT.relative_to(REPO))
    print("construction goods: %d (%d standard)" % (len(goods), len(STANDARD)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
