#!/usr/bin/env python3
"""Generate the per-good price readings this mod is built on.

For every good the game charges construction in, emit a script value giving that
good's construction cost impact in the country's own market, as a percentage:

    bgt_impact_lumber   -33.0  lumber is as cheap as the engine will credit
                          0.0  lumber sits at its default price
                        +12.5  lumber is dear and construction costs more

The formula is not ours. It is Glorp UI's `glorpui_construction_good_adjustment`,
which Construction Manager uses for its own minimum-discount gates, so the number
this mod shows and the number CM gates on cannot drift apart. Written out per
good rather than called, because that value expects `scope:cm_location` and this
mod asks the question of a country.

The list of goods is read from Construction Manager, not typed here: its
`cm_construction_demand_<good>` maps are the game's construction goods, and if a
patch adds one, this picks it up on the next run.

    python3 mods/goods_target/tools/generate.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(REPO / "tools"))

import eu5data  # noqa: E402
import refs  # noqa: E402

OUT = MOD / "in_game/common/script_values/bgt_generated_values.txt"
LIST_OUT = MOD / "in_game/common/scripted_effects/bgt_generated_list.txt"
LOC_OUT = MOD / "main_menu/localization/%s/bgt_generated_l_%s.yml"
LOC_LANGUAGES = ("english", "russian")

CM_COSTS = "in_game/common/script_values/cm_construction_cost_adjustments_script_values.txt"
DEMAND_MAP = re.compile(r"cm_construction_demand_([a-z_]+)")
# The subset CM calls "standard": the goods a player can actually depress by
# building more of them. The rest — gold, tools, paper — do not respond.
STANDARD = ("lumber", "masonry", "glass", "sand", "stone")

HEADER = """\
# Generated by mods/goods_target/tools/generate.py. Do not edit by hand.
#
# One value per construction good: what that good's market price is doing to the
# cost of building things, as a percentage. Negative is a discount. The engine
# credits at most -33% (define:NMarket|MIN_PRICE_IMPACT) once every input is
# weighted, and a single good reaches that only when it is the whole recipe.
#
# Root is the country. The market read is the capital's.
"""

VALUE = """\
bgt_impact_%(good)s = {
\tgoods:%(good)s = { save_temporary_scope_as = bgt_good }
\tif = {
\t\tlimit = { "capital.market.market_price(scope:bgt_good)" > "default_price(scope:bgt_good)" }
\t\tvalue = "capital.market.market_price(scope:bgt_good)"
\t\tdivide = "default_price(scope:bgt_good)"
\t\tsubtract = 1
\t\tdivide = 2
\t}
\telse_if = {
\t\tlimit = { "capital.market.market_price(scope:bgt_good)" < "default_price(scope:bgt_good)" }
\t\tvalue = "capital.market.market_price(scope:bgt_good)"
\t\tdivide = "default_price(scope:bgt_good)"
\t\tsubtract = 1
\t\tmultiply = {
\t\t\tvalue = 1
\t\t\tdivide = 9
\t\t\tadd = 1
\t\t}
\t}
\telse = { value = 0 }
\tmultiply = 100
\tmin = -33
\tmax = 300
}
"""


LIST_HEADER = """\
# Generated by mods/goods_target/tools/generate.py. Do not edit by hand.
#
# The goods list the player ticks in, and the lookup rebuild that turns those
# ticks into something script can read.
#
# Two things here are not free choices. Item ordinals are literals, because a
# CMM list macro pastes `item = var:x` verbatim and the load dies on it. And the
# list is registered at its full height once: CMM's dynamic builder runs only
# before `cmm_list_initialized_<setting>` is set, and re-registration only ever
# adds rows.
#
# Scope: country

bgt_register_goods_list = {
\tcmm_register_settings_list = {
\t\tmod_id = bgt
\t\tsetting_id = goods
\t\ttab_id = main
\t\titem_count = %(count)d
\t\tis_ordered = 1
\t}

%(items)s
\t# Field slots follow registration order: build is 1, subsidise is 2.
\tcmm_register_list_bool_field = {
\t\tmod_id = bgt
\t\tsetting_id = goods
\t\tfield_id = build
\t\tdefault_value = 0
\t}

\tcmm_register_list_bool_field = {
\t\tmod_id = bgt
\t\tsetting_id = goods
\t\tfield_id = subsidise
\t\tdefault_value = 0
\t}
}

# Turn the ticks into variable lists a trigger can ask about. Called on
# registration and from the list's _on_changed scripted GUI, which is the only
# route a click on a list takes into script -- CMM's auto-apply covers bool,
# dropdown, numeric, slider and button settings, and not lists.
# Scope: country
bgt_rebuild_lookups = {
\tif = {
\t\t# Registration may not have completed yet on the first pass.
\t\tlimit = { has_variable_list = cmm_list_items_bgt__goods }
\t\tcmm_build_list_ordered_values = { setting = bgt__goods list_name = bgt_goods_list }
\t\tcmm_build_list_bool_list = { setting = bgt__goods field_slot = 1 list_name = bgt_goods_build }
\t\tcmm_build_list_bool_list = { setting = bgt__goods field_slot = 2 list_name = bgt_goods_subsidise }
\t}
}
"""

ITEM = "\tcmm_set_list_item_value = { mod_id = bgt setting_id = goods item = %(n)d value = goods:%(good)s }"


SETTING = re.compile(
    r"cmm_register_(bool|numeric|slider|dropdown|text|button|settings_list)_setting\b|"
    r"cmm_register_settings_list\b|cmm_register_list_(bool|numeric|slider|text)_field\b")
ARG = re.compile(r"(\w+)\s*=\s*([\w:]+)")
KEY_LINE = re.compile(r'^\s*([A-Za-z0-9_.]+):\s*"')


def required_keys() -> set[str]:
    """The localization keys CMM will look for, derived the way CMM derives them.

    A missing one is not an error anywhere -- the raw key name simply appears on
    screen, in the middle of the framework's own interface.
    """
    text = "".join(p.read_text(encoding="utf-8-sig")
                   for p in sorted((MOD / "in_game/common/scripted_effects").glob("*.txt")))
    keys = {"bgt_name", "bgt_desc"}
    for call in re.finditer(r"(cmm_register_\w+) = \{([^{}]*)\}", text):
        name, args = call.group(1), dict(ARG.findall(call.group(2)))
        mod, setting = args.get("mod_id"), args.get("setting_id")
        if not mod or not setting:
            continue
        if "list_" in name and "field_id" in args:
            keys.add(f"{mod}__{setting}__{args['field_id']}_name")
            continue
        if name.endswith("settings_list"):
            # A list is its own group, so its header is keyed through the tab.
            keys.add(f"{mod}__{args['tab_id']}__{setting}_name")
            keys.add(f"{mod}__{setting}_item_column_name")
            continue
        keys.add(f"{mod}__{setting}_name")
        if "tab_id" in args:
            keys.add(f"{mod}__{args['tab_id']}_name")
        if "group_id" in args:
            keys.add(f"{mod}__{args['tab_id']}__{args['group_id']}_name")
    return keys


def check_localization() -> list[str]:
    """Every derived key defined, in every language, and the languages in step."""
    defined = {}
    for language in LOC_LANGUAGES:
        folder = MOD / "main_menu/localization" / language
        keys = set()
        for path in sorted(folder.glob("*.yml")):
            for line in path.read_text(encoding="utf-8-sig").splitlines():
                match = KEY_LINE.match(line)
                if match:
                    keys.add(match.group(1))
        defined[language] = keys

    problems = []
    for language, keys in defined.items():
        for key in sorted(required_keys() - keys):
            problems.append(f"{language}: no localization for {key}")
    first, *rest = LOC_LANGUAGES
    for language in rest:
        for key in sorted(defined[first] ^ defined[language]):
            problems.append(f"{key} is in one language and not the other")
    return problems


def write(path: Path, text: str) -> None:
    """Every file the game reads carries a UTF-8 BOM."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8")
    print("wrote %s" % path.relative_to(REPO))


def ordered(goods: list[str]) -> list[str]:
    """Standard construction goods first — they are what the mod is for."""
    rest = [g for g in goods if g not in STANDARD]
    return [g for g in STANDARD if g in goods] + rest


def construction_goods() -> list[str]:
    """The goods the game charges construction in, per Construction Manager."""
    path = refs.known("construction_manager") / CM_COSTS
    if not path.is_file():
        raise SystemExit(f"no construction cost values at {path}")
    found = sorted(set(DEMAND_MAP.findall(path.read_text(encoding="utf-8-sig"))))
    if not found:
        raise SystemExit(f"no cm_construction_demand_<good> maps in {path.name}")
    return found


def main() -> int:
    goods = construction_goods()
    catalogue = eu5data.load_game().all_goods

    unknown = [g for g in goods if g not in catalogue]
    if unknown:
        # CM names goods_gold where the catalogue says gold; anything else here
        # means a patch renamed a good and this mod would emit a dead value.
        print("not in the goods catalogue, skipped: %s" % ", ".join(unknown),
              file=sys.stderr)
        goods = [g for g in goods if g in catalogue]

    missing = [g for g in STANDARD if g not in goods]
    if missing:
        raise SystemExit("CM no longer charges construction in %s — the standard "
                         "goods this mod is about have moved" % ", ".join(missing))

    goods = ordered(goods)

    body = [HEADER]
    for good in goods:
        body.append(VALUE % {"good": good})
    write(OUT, "\n".join(body))

    items = "\n".join(ITEM % {"n": n, "good": good}
                      for n, good in enumerate(goods, start=1))
    write(LIST_OUT, LIST_HEADER % {"count": len(goods), "items": items + "\n"})

    # A row's label is the game's own name for the good behind a texticon, so
    # the same generated file serves every language the mod ships.
    labels = ['bgt__goods_i%d_name: "@%s! [ShowGoodsName(\'%s\')]"' % (n, good, good)
              for n, good in enumerate(goods, start=1)]
    for language in LOC_LANGUAGES:
        lines = ["l_%s:" % language] + [" " + label for label in labels]
        write(Path(str(LOC_OUT) % (language, language)), "\n".join(lines) + "\n")

    print("construction goods: %d (%d standard, listed first)"
          % (len(goods), len(STANDARD)))

    problems = check_localization()
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        print("%d localization problems" % len(problems), file=sys.stderr)
        return 1
    print("localization: every derived CMM key defined, both languages in step")
    return 0


if __name__ == "__main__":
    sys.exit(main())
