#!/usr/bin/env python3
"""Generate the per-good price readings this mod is built on.

For every good the game charges construction in, emit a script value giving that
good's construction cost impact in the country's own market, as a percentage:

    bgt_impact_lumber   -33.0  lumber is as cheap as the engine will credit
                          0.0  lumber sits at its default price
                        +12.5  lumber is dear and construction costs more

The formula is not ours. It is Glorp UI's `glorpui_construction_good_adjustment`,
which Construction Manager uses for its own minimum-discount gates, so the number
this mod shows and the number CM gates on cannot drift apart. Written out per
good rather than called, because that value expects `scope:cm_location` and this
mod asks the question of a country.

Every good in the game gets one, not only the goods construction is charged in:
a player may want cannons or cloth cheap for their own sake. Which goods the
game actually charges construction in is still read from Construction Manager's
`cm_construction_demand_<good>` maps, because those are the ones where a cheaper
price shows up as a build discount, and they are listed first.

    python3 mods/goods_target/tools/generate.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(REPO / "tools"))

import check_cmm  # noqa: E402  the shared CMM checker
import eu5data  # noqa: E402
import refs  # noqa: E402

OUT = MOD / "in_game/common/script_values/bgt_generated_values.txt"
LIST_OUT = MOD / "in_game/common/scripted_effects/bgt_generated_list.txt"
LOC_OUT = MOD / "main_menu/localization/%s/bgt_generated_l_%s.yml"
LOC_LANGUAGES = ("english", "russian")

CM_COSTS = "in_game/common/script_values/cm_construction_cost_adjustments_script_values.txt"
DEMAND_MAP = re.compile(r"cm_construction_demand_([a-z_]+)")
# The subset CM calls "standard": the goods a player can actually depress by
# building more of them. The rest — gold, tools, paper — do not respond.
STANDARD = ("lumber", "masonry", "glass", "sand", "stone")
# CMF initialises list items through an unrolled chain that ends here.
LIST_LIMIT = 50
# Rows in the list, and their fields. Field slots follow registration order.
FIELDS = (("build", "bool"), ("subsidise", "bool"), ("target", "numeric"))

HEADER = """\
# Generated by mods/goods_target/tools/generate.py. Do not edit by hand.
#
# One value per construction good: what that good's market price is doing to the
# cost of building things, as a percentage. Negative is a discount. The engine
# credits at most -33% (define:NMarket|MIN_PRICE_IMPACT) once every input is
# weighted, and a single good reaches that only when it is the whole recipe.
#
# Root is the country. The market read is the capital's.
"""

VALUE = """\
bgt_impact_%(good)s = {
\tgoods:%(good)s = { save_temporary_scope_as = bgt_good }
\tif = {
\t\tlimit = { "capital.market.market_price(scope:bgt_good)" > "default_price(scope:bgt_good)" }
\t\tvalue = "capital.market.market_price(scope:bgt_good)"
\t\tdivide = "default_price(scope:bgt_good)"
\t\tsubtract = 1
\t\tdivide = 2
\t}
\telse_if = {
\t\tlimit = { "capital.market.market_price(scope:bgt_good)" < "default_price(scope:bgt_good)" }
\t\tvalue = "capital.market.market_price(scope:bgt_good)"
\t\tdivide = "default_price(scope:bgt_good)"
\t\tsubtract = 1
\t\tmultiply = {
\t\t\tvalue = 1
\t\t\tdivide = 9
\t\t\tadd = 1
\t\t}
\t}
\telse = { value = 0 }
\tmultiply = 100
\tmin = -33
\tmax = 300
}
"""


# CMF's list registration is an unrolled chain of `if`s that stops at item 50,
# so a list longer than that silently loses its tail. 74 goods therefore come as
# two lists, split where the split means something: the goods construction is
# charged in, and everything else.
LISTS = (
    ("construction", "the goods construction is charged in"),
    ("other", "every other good in the game"),
)

LIST_HEADER = """\
# Generated by mods/goods_target/tools/generate.py. Do not edit by hand.
#
# The goods lists the player ticks in, and the lookup rebuild that turns those
# ticks into something script can read.
#
# Three things here are not free choices:
#
#   - Item ordinals are literals. A CMM list macro pastes `item = var:x`
#     verbatim and the load dies on it.
#   - Each list is registered at its full height once. CMM's dynamic builder
#     runs only before `cmm_list_initialized_<setting>` is set, and
#     re-registration only ever adds rows.
#   - There are two lists rather than one. CMF initialises list items through an
#     unrolled chain that ends at item 50, so rows past it would be registered
#     and then never initialised -- present in the count, absent from the
#     interface, and silent about it.
#
# Scope: country
"""

LIST_BODY = """
bgt_register_%(list)s_list = {
\tcmm_register_settings_list = {
\t\tmod_id = bgt
\t\tsetting_id = %(list)s
\t\ttab_id = main
\t\titem_count = %(count)d
\t\tis_ordered = 1
\t}

%(items)s
\t# Field slots follow registration order: build is 1, subsidise is 2,
\t# target is 3. bgt_rebuild_lookups reads them back by those numbers.
\tcmm_register_list_bool_field = {
\t\tmod_id = bgt
\t\tsetting_id = %(list)s
\t\tfield_id = build
\t\tdefault_value = 0
\t}

\tcmm_register_list_bool_field = {
\t\tmod_id = bgt
\t\tsetting_id = %(list)s
\t\tfield_id = subsidise
\t\tdefault_value = 0
\t}

\t# The discount this good should reach, one figure per good rather than one
\t# for all of them. Negative is a discount; the engine credits at most -33%%.
\tcmm_register_list_numeric_field = {
\t\tmod_id = bgt
\t\tsetting_id = %(list)s
\t\tfield_id = target
\t\tdefault_value = -33
\t\tmin_value = -33
\t\tmax_value = 0
\t\tstep_value = 1
\t}
\tcmm_set_list_field_conditional_format = { mod_id = bgt setting_id = %(list)s field_id = target }
}
"""

REBUILD = """
# Turn the ticks into variable lists and maps a trigger can ask about. Called on
# registration and from each list's _on_changed scripted GUI, which is the only
# route a click on a list takes into script -- CMM's auto-apply covers bool,
# dropdown, numeric, slider and button settings, and not lists.
#
# The two lists keep their own results rather than being merged, because
# `cmm_build_list_bool_list` clears the list it writes into: a merge would leave
# only whichever ran last. Anything reading these has to read both.
# Scope: country
bgt_register_lists = {
%(register)s}

bgt_rebuild_lookups = {
%(rebuild)s}
"""

REBUILD_ONE = """\tif = {
\t\t# Registration may not have completed yet on the first pass.
\t\tlimit = { has_variable_list = cmm_list_items_bgt__%(list)s }
\t\tcmm_build_list_ordered_values = { setting = bgt__%(list)s list_name = bgt_%(list)s_goods }
\t\tcmm_build_list_bool_list = { setting = bgt__%(list)s field_slot = 1 list_name = bgt_%(list)s_build }
\t\tcmm_build_list_bool_list = { setting = bgt__%(list)s field_slot = 2 list_name = bgt_%(list)s_subsidise }
\t\tcmm_build_list_field_map = { setting = bgt__%(list)s field_slot = 3 map_name = bgt_%(list)s_target multiply = 1 }
\t}
"""

ITEM = "\tcmm_set_list_item_value = { mod_id = bgt setting_id = %(list)s item = %(n)d value = goods:%(good)s }"


def write(path: Path, text: str) -> None:
    """Every file the game reads carries a UTF-8 BOM."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("﻿" + text, encoding="utf-8")
    print("wrote %s" % path.relative_to(REPO))


def ordered(construction: list[str], every: set[str]) -> list[str]:
    """Every good, most useful first.

    The five a player can actually depress lead, then the rest of the goods
    construction is charged in, then everything else. A good further down is not
    less real — cannons and cloth are worth wanting cheap — it just cannot show
    up as a construction discount.
    """
    standard = [g for g in STANDARD if g in every]
    rest_construction = sorted(g for g in construction
                               if g in every and g not in STANDARD)
    other = sorted(every - set(standard) - set(rest_construction))
    return standard + rest_construction + other


def construction_goods() -> list[str]:
    """The goods the game charges construction in, per Construction Manager."""
    path = refs.known("construction_manager") / CM_COSTS
    if not path.is_file():
        raise SystemExit(f"no construction cost values at {path}")
    found = sorted(set(DEMAND_MAP.findall(path.read_text(encoding="utf-8-sig"))))
    if not found:
        raise SystemExit(f"no cm_construction_demand_<good> maps in {path.name}")
    return found


def main() -> int:
    construction = construction_goods()
    catalogue = eu5data.load_game().all_goods

    unknown = [g for g in construction if g not in catalogue]
    if unknown:
        # A good Construction Manager charges for that the game's own catalogue
        # does not have means a patch renamed one, and a dead row would follow.
        print("charged for by CM but not in the goods catalogue: %s"
              % ", ".join(unknown), file=sys.stderr)

    missing = [g for g in STANDARD if g not in construction]
    if missing:
        raise SystemExit("CM no longer charges construction in %s — the standard "
                         "goods this mod is about have moved" % ", ".join(missing))

    goods = ordered(construction, catalogue)

    body = [HEADER]
    for good in goods:
        body.append(VALUE % {"good": good})
    write(OUT, "\n".join(body))

    # Which goods go in which list, in the order the rows appear.
    rows = {
        "construction": [g for g in goods if g in construction],
        "other": [g for g in goods if g not in construction],
    }
    for name, members in rows.items():
        if len(members) > LIST_LIMIT:
            raise SystemExit(
                "the %s list would be %d rows and CMF initialises at most %d; "
                "rows past that are registered and never drawn"
                % (name, len(members), LIST_LIMIT))

    parts = [LIST_HEADER]
    for name, _ in LISTS:
        items = "\n".join(ITEM % {"list": name, "n": n, "good": good}
                           for n, good in enumerate(rows[name], start=1))
        parts.append(LIST_BODY % {"list": name, "count": len(rows[name]),
                                  "items": items + "\n"})
    parts.append(REBUILD % {
        "register": "".join("\tbgt_register_%s_list = yes\n" % name for name, _ in LISTS),
        "rebuild": "".join(REBUILD_ONE % {"list": name} for name, _ in LISTS),
    })
    write(LIST_OUT, "".join(parts))

    # A row's label is the game's own name for the good behind a texticon, with
    # what that good is doing to build costs right now beside it -- the figure
    # the tick is a decision about. None of it is a word, so the same generated
    # file serves every language the mod ships.
    labels = []
    for name, _ in LISTS:
        for n, good in enumerate(rows[name], start=1):
            labels.append(
                'bgt__%s_i%d_name: "@%s! [ShowGoodsName(\'%s\')] '
                '([GuiScope.SetRoot(GetPlayer.MakeScope).ScriptValue(\'bgt_impact_%s\')|1]%%)"'
                % (name, n, good, good, good))
    for language in LOC_LANGUAGES:
        lines = ["l_%s:" % language] + [" " + label for label in labels]
        write(Path(str(LOC_OUT) % (language, language)), "\n".join(lines) + "\n")

    print("goods: %d in %d lists (%d charged for by construction, %d depressible)"
          % (len(goods), len(LISTS), len(construction), len(STANDARD)))

    problems = check_cmm.check_localization(MOD / "in_game/common")
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        print("%d localization problems" % len(problems), file=sys.stderr)
        return 1
    print("localization: every key CMM derives is defined, languages in step")
    return 0


if __name__ == "__main__":
    sys.exit(main())
