#!/usr/bin/env python3
"""Build the override file that repairs the game's Russian localization.

    python3 mods/ru_loc_fix/tools/generate.py

A mod that defines a key the game already defines wins, so every repair in this
mod is one line: the game's key, written again with its markup fixed. What this
tool does is decide *what* to write, and refuse to write anything it cannot
justify.

There are two ways to say how a key should be repaired.

**A rewrite** (`fixes/rewrites.txt`) is a search and replace applied to whatever
the game currently ships. `.GetAdjectvive` becomes `.GetAdjective` wherever the
scanner found a broken key, and the Russian prose around it comes along
untouched. This is the better of the two, and worth reaching for even when the
repair only makes sense on one key — write `key:` above it and it applies there
alone. When Paradox next edits that sentence the mod picks up their new wording
and still repairs the fault. Rewrites are applied in file order to every key a
hard rule in `locscan` flags and to every key named in `fixes/observed.txt`.

**A literal** (`fixes/*.yml`, ordinary localization files) is the whole value,
written out. Used where the repair takes judgement — a bracket can be closed in
more than one place, and only a person can say which one the sentence meant. A
literal freezes the Russian text as it was on the day it was written, so the
generator checks the key still exists and still needs fixing, and says so when
Paradox has moved on.

Nothing ships unless it can be justified and shown to work:

* the key has to still be defined by the game — a key that vanished is reported,
  not silently carried;
* the key has to still be broken — one that a patch repaired is reported so the
  override can be dropped, because an override of a healthy key is just an old
  translation held in place;
* being broken means either a hard rule in `locscan` fires on it, or it is
  listed in `fixes/observed.txt` with what the game logged, for the faults no
  rule can see from the files alone;
* and the repaired value has to pass every hard rule. A fix that trades one
  fault for another does not get written.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(MOD / "tools"))
import locscan  # noqa: E402

FIXES = MOD / "fixes"
REWRITES = FIXES / "rewrites.txt"
OBSERVED = FIXES / "observed.txt"
OUT = MOD / "main_menu/localization/russian/bag_ruloc_generated_l_russian.yml"

HEADER = """\
# Generated by mods/ru_loc_fix/tools/generate.py — do not edit by hand.
#
# Each key below is defined by the game's own Russian localization with damaged
# markup, and is written again here with the markup repaired. The reason for
# each is in mods/ru_loc_fix/fixes/; run
#
#     python3 mods/ru_loc_fix/tools/locscan.py
#
# to see what is still broken in the game's files.
"""


def read_rewrites(path: Path) -> list[tuple[str | None, str, str, str]]:
    """The `from:`/`to:` pairs, in file order, each with its `key:` and `why:`.

    A pair with no `key:` immediately above it is applied to every flagged key;
    one with a `key:` is applied only to that key. `key:` governs the one pair
    that follows it and then falls away, so a global rewrite written after a
    keyed one stays global. `why:` carries over until it is set again.
    """
    pairs: list[tuple[str | None, str, str, str]] = []
    why, key = "", None
    pending: str | None = None
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        label, _, rest = stripped.partition(":")
        rest = rest.strip()
        if label == "why":
            why = rest
        elif label == "key":
            key = rest or None
        elif label == "from":
            pending = rest
        elif label == "to":
            if pending is None:
                raise SystemExit("%s:%d: 'to:' with no 'from:' before it" % (path.name, number))
            pairs.append((key, pending, rest, why))
            pending, key = None, None
        else:
            raise SystemExit("%s:%d: expected key:/why:/from:/to:, got %r"
                             % (path.name, number, label))
    if pending is not None:
        raise SystemExit("%s: a 'from:' at the end with no 'to:'" % path.name)
    return pairs


def read_literals(directory: Path) -> dict[str, tuple[str, Path, int]]:
    """The hand written replacement values, from ordinary localization files."""
    values: dict[str, tuple[str, Path, int]] = {}
    for path in sorted(directory.glob("*.yml")):
        for number, line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
            match = locscan.KEY_LINE.match(line)
            if match:
                key, value = match.groups()
                values[key] = (value, path, number)
    return values


def read_observed(path: Path) -> dict[str, str]:
    """Keys the game itself reported broken, and the line that reported them."""
    seen: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, _, evidence = stripped.partition(" ")
        seen[key] = evidence.strip()
    return seen


def main() -> int:
    russian, english = locscan.load()
    flagged = {f.key: f for f in locscan.scan(russian, english, locscan.HARD)}
    observed = read_observed(OBSERVED)
    rewrites = read_rewrites(REWRITES)
    literals = read_literals(FIXES)

    fixed: dict[str, str] = {}
    complaints: list[str] = []

    # Rewrites, against every key a hard rule flags. A pair that changes nothing
    # on any key is dead weight and worth knowing about, so they are counted.
    used = {pair: 0 for pair in rewrites}
    for key in sorted(set(flagged) | set(observed)):
        if key not in russian:
            continue
        value = russian[key].value
        for pair in rewrites:
            only, pattern, replacement, _ = pair
            if only is not None and only != key:
                continue
            if pattern in value:
                value = value.replace(pattern, replacement)
                used[pair] += 1
        if value != russian[key].value:
            fixed[key] = value
    for (only, pattern, _, why), count in used.items():
        if count:
            continue
        if only is not None and only not in flagged:
            complaints.append("rewrite for %s: the game's key is no longer flagged by any "
                              "rule — either a patch fixed it, or the rule stopped seeing it"
                              % only)
        else:
            complaints.append("rewrite %r matched nothing — %s" % (pattern, why))

    # Literals override rewrites: they were written because the rewrite could
    # not express the repair.
    for key, (value, path, number) in literals.items():
        if key not in russian:
            complaints.append("%s:%d: the game no longer defines %s" % (path.name, number, key))
            continue
        if key not in flagged and key not in observed:
            complaints.append(
                "%s:%d: %s is no longer flagged by any rule and is not in observed.txt "
                "— either the game fixed it, or say what the game logged"
                % (path.name, number, key))
            continue
        fixed[key] = value

    # Every shipped value has to survive the rules it was written to satisfy.
    entries = {k: locscan.Entry(k, v, OUT, 0) for k, v in fixed.items()}
    for finding in locscan.scan(entries, english, locscan.HARD):
        complaints.append("the fix for %s still trips %s: %s"
                          % (finding.key, finding.rule, finding.detail))
    for key, value in fixed.items():
        if '"' in value:
            complaints.append("the fix for %s contains a double quote, "
                              "which truncates the line in game" % key)

    if complaints:
        for line in complaints:
            print("     %s" % line)
        print("     refusing to write %s" % OUT.relative_to(MOD.parent.parent))
        return 1

    lines = [HEADER, "l_russian:"]
    for key in sorted(fixed):
        lines.append(' %s:0 "%s"' % (key, fixed[key]))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("﻿" + "\n".join(lines) + "\n", encoding="utf-8")

    by_rewrite = sum(1 for k in fixed if k not in literals)
    left = sorted(set(flagged) - set(fixed))
    print("wrote %s" % OUT.relative_to(MOD.parent.parent))
    print("     %d keys repaired: %d by rewrite, %d written out"
          % (len(fixed), by_rewrite, len(fixed) - by_rewrite))
    print("     %d keys the hard rules still flag and this mod does not fix" % len(left))
    for key in left[:20]:
        print("       %s  (%s)" % (key, flagged[key].rule))
    if len(left) > 20:
        print("       ... and %d more" % (len(left) - 20))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
