#!/usr/bin/env python3
"""Generate everything `where_to_produce` cannot write by hand.

The mod answers one question: **for this good, where is the best place to make
it, and with what.** The player names a good; the mod finds, per location, the
best production method available for that good there, and ranks the locations by
what that method would earn from the raw materials the province supplies.

Choosing the method was the player's job for one round and it should not have
been: knowing which recipe suits which ground *is* the question the mod exists to
answer, so asking it back was asking the player to do the work first.

Four things come out of the game's own files rather than out of a list somebody
typed, so a patch that adds a method or renames a region is picked up by a
rebuild:

  - **The good picker.** Two lists, split the way the goods themselves are: the
    25 raw materials an RGO can also make, and the 22 things only a workshop
    makes. Lists rather than dropdowns -- CMF handles a dropdown option click
    through `CMM_MarkDropdownSelection_<index>` and defines twenty of them, so a
    dropdown is silently unclickable past its twentieth option. A list is handled
    to fifty.
  - **The zone.** The five land continents, ticked. Not a walk: a location's
    continent is one plain trigger, so nothing has to be marked in advance.
  - **The scoring.** One script value per method giving what it would earn here,
    and one effect per good that runs its methods over the candidates and keeps
    the best. That is where "the mod finds the method" actually happens.
  - **The result rows.** Fifty of them, each reading back a location, a number
    and the building that won it.

The formula is `eu5data.Method.bonus`, verified to the digit against three
in-game tooltips at 1.3.10. See `docs/research/engine.md`.

    python3 mods/where_to_produce/tools/generate.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(REPO / "tools"))

import eu5data  # noqa: E402
import refs  # noqa: E402

MOD_ID = "bag_wtp"

# How many rows any list has at most. CMF initialises list items through an
# unrolled chain of `if`s that ends at fifty, and handles a row click through
# `CMM_MarkListPosition_*`, which is unrolled to the same fifty. Raising this
# means leaving CMM, not editing this number.
LIST_CAP = 50
RESULT_ROWS = 50

# Raw materials a single method can want. The widest recipe in the game takes
# five.
MAX_INPUTS = 5

# The land continents, in the order the game's own localization lists them. The
# ocean continent is not offered: nothing is built there.
CONTINENTS = ("europe", "asia", "africa", "america", "oceania")

# One tab per job. A CMM tab is just a `tab_id` on the settings under it, so this
# costs nothing but the three localization keys -- and the first build had five
# groups stacked on one tab, which meant scrolling past the goods to reach the
# answer.
TAB_GOODS = "goods"
TAB_ZONE = "zone"
TAB_PLAN = "plan"

ZONE_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_zone.txt"
REGION_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_regions.txt"
PICKER_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_picker.txt"
SCORE_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_score.txt"
ROWS_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_rows.txt"
VALUES_OUT = MOD / "in_game/common/script_values/bag_wtp_generated_values.txt"
TRIGGERS_OUT = MOD / "in_game/common/scripted_triggers/bag_wtp_generated_triggers.txt"
GUIS_OUT = MOD / "in_game/common/scripted_guis/bag_wtp_generated_scripted_gui.txt"
LOC_OUT = MOD / "main_menu/localization/%s/bag_wtp_generated_l_%s.yml"
LOC_LANGUAGES = ("english", "russian")

BOM = "﻿"
HEADER = "# Generated by mods/where_to_produce/tools/generate.py. Do not edit by hand.\n"


def unlocks() -> dict[str, str]:
    """Production method -> the advance that unlocks it.

    Only ten methods are gated this way; the rest ride on their building's own
    unlock, of which there are 119 with an age attached. Both are asked through
    `can_build_building` in country scope and `has_advance`.
    """
    out: dict[str, str] = {}
    for path in (refs.GAME / "in_game/common/advances").glob("*.txt"):
        text = path.read_text(encoding="utf-8-sig")
        for block in re.finditer(r"^([a-z0-9_]+)\s*=\s*\{(.*?)^\}", text, re.S | re.M):
            for method in re.findall(r"unlock_production_method\s*=\s*([a-z0-9_]+)",
                                     block.group(2)):
                out[method] = block.group(1)
    return out


UNLOCKS = unlocks()


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(BOM + body, encoding="utf-8")


# --------------------------------------------------------------------------
# What the game offers


def methods(game: eu5data.Game) -> list[eu5data.Method]:
    """Every method that could gain something from an RGO.

    A method with no raw-material input can never take the bonus, so scoring it
    would be scoring a zero.
    """
    rows = [m for m in game.methods if m.raw_inputs(game.raw_goods)]
    return sorted(rows, key=lambda m: (m.produced, m.building, m.key))


def goods_split(rows: list[eu5data.Method], game: eu5data.Game) -> dict[str, list[str]]:
    """The goods worth asking about, split into the two piles the player thinks in.

    A raw material is something an RGO also produces -- so a mason's yard and a
    quarry both make masonry, and the question "where should I make it" is a
    different one from "where should I make cannons".
    """
    goods = sorted({m.produced for m in rows})
    split = {
        "raw": [g for g in goods if g in game.raw_goods],
        "made": [g for g in goods if g not in game.raw_goods],
    }
    over = {k: len(v) for k, v in split.items() if len(v) > LIST_CAP}
    if over:
        raise SystemExit(f"a goods list is taller than CMM holds: {over}")
    return split


# --------------------------------------------------------------------------
# Output


def regions() -> dict[str, list[str]]:
    """Continent -> region keys, read off the game's own region localization.

    The file carries the hierarchy in its comments and it is the only place in
    `reference/` that knows it, because `map_data` is not in the tree. Two
    cautions, both paid for: five real regions sit under "Subcontinents" and
    `poland` is a region without the `_region` suffix, so the suffix is honoured
    wherever it appears and the Regions section counts on its own; and filtering
    water by name throws out `north_atlantic_islands_region`, which is dry land,
    so the file's own "Ocean Subcontinent" grouping does that job instead.
    """
    path = refs.GAME_LOCALIZATION / "english/region_names_l_english.yml"
    out: dict[str, list[str]] = {}
    seen: set[str] = set()
    section = continent = group = None
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("l_english"):
            continue
        indent = len(line) - len(line.lstrip())
        if stripped.startswith("#"):
            name = stripped.lstrip("#").strip()
            if indent <= 1:
                section, continent, group = name, None, None
            elif indent <= 2:
                continent, group = name, None
            else:
                group = name
            continue
        match = re.match(r"^([a-z0-9_]+):", stripped)
        if not match or continent is None:
            continue
        key = match.group(1)
        if not (key.endswith("_region") or section == "Regions"):
            continue
        if group == "Ocean Subcontinent" or key in seen:
            continue
        seen.add(key)
        out.setdefault(continent.lower(), []).append(key)
    over = {c: len(r) for c, r in out.items() if len(r) > LIST_CAP}
    if over:
        raise SystemExit(f"a continent has more regions than a CMM list holds: {over}")
    return {c: r for c, r in out.items() if c in CONTINENTS}


def region_file(by_continent: dict[str, list[str]]) -> str:
    """The regions, one list per continent, all on the zone tab.

    Ticking a whole continent paints the screen red and is a blunt frame; the
    good case is one region ticked, its ground offered and everything else left
    alone, with a neighbour addable beside it. Both are here: a continent row and
    a region row do the same thing to the same list.
    """
    out = [HEADER, "#\n# Scope: country\n"]
    for continent, keys in by_continent.items():
        out.append(f"""
{MOD_ID}_register_region_{continent}_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = region_{continent}
\t\ttab_id = {TAB_ZONE}
\t\titem_count = {len(keys)}
\t\tis_ordered = 0
\t}}

""")
        for index, key in enumerate(keys, start=1):
            out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                       f"setting_id = region_{continent} item = {index} value = region:{key} }}\n")
        out.append("\n")
        for index, key in enumerate(keys, start=1):
            out.append(f"\tset_variable = {{ name = {MOD_ID}__region_{continent}_i{index}_name "
                       f"value = flag:{key} }}\n")
        out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = region_{continent}
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}
""")

    out.append(f"\n# Scope: country\n{MOD_ID}_register_region_lists = {{\n")
    for continent in by_continent:
        out.append(f"\t{MOD_ID}_register_region_{continent}_list = yes\n")
    out.append("}\n")

    out.append(f"""
# The ticked regions, gathered beside the ticked continents. Both narrow the same
# search; a region is simply the finer of the two.
# Scope: country
{MOD_ID}_rebuild_regions = {{
\tclear_global_variable_list = {MOD_ID}_regions
\tset_global_variable = {{ name = {MOD_ID}_region_count value = 0 }}
""")
    for continent in by_continent:
        out.append(f"""\tif = {{
\t\tlimit = {{ has_variable_list = cmm_list_items_{MOD_ID}__region_{continent} }}
\t\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__region_{continent} field_slot = 1 list_name = {MOD_ID}_region_{continent}_ticks }}
\t\tevery_in_list = {{
\t\t\tvariable = {MOD_ID}_region_{continent}_ticks
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_regions target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_region_count add = 1 }}
\t\t}}
\t}}
""")
    out.append("}\n")

    out.append(f"""
# Every land location of the ticked regions, for the ranking's fallback.
# Scope: country
{MOD_ID}_collect_regions = {{
\tevery_in_global_list = {{
\t\tvariable = {MOD_ID}_regions
\t\tevery_location_in_region = {{
\t\t\tlimit = {{ {MOD_ID}_is_candidate = yes }}
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_candidates target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_candidate_count add = 1 }}
\t\t}}
\t}}
}}
""")
    return "".join(out)


def zone_file() -> str:
    """The zone: the continents to look inside, ticked.

    There is nothing to walk here. A location's continent is a plain trigger --
    `continent = continent:europe`, which vanilla uses seventy times -- so
    membership is asked at the moment it matters instead of being marked onto
    every location of a continent in advance. An earlier version did the walk,
    and ticking Europe would have meant setting a variable on some thousands of
    locations for nothing.
    """
    out = [HEADER, f"""#
# Scope: country
{MOD_ID}_register_zone_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = continent
\t\ttab_id = {TAB_ZONE}
\t\titem_count = {len(CONTINENTS)}
\t\tis_ordered = 0
\t}}

"""]
    for index, key in enumerate(CONTINENTS, start=1):
        out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                   f"setting_id = continent item = {index} value = continent:{key} }}\n")
    out.append("\n")
    for index, key in enumerate(CONTINENTS, start=1):
        # The game's own key, so the row arrives named in the player's language
        # and nothing here carries a copy of it.
        out.append(f"\tset_variable = {{ name = {MOD_ID}__continent_i{index}_name "
                   f"value = flag:{key} }}\n")
    out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = continent
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}

# Scope: country
{MOD_ID}_rebuild_zone = {{
\tclear_global_variable_list = {MOD_ID}_continents
\tset_global_variable = {{ name = {MOD_ID}_zone_count value = 0 }}

\tif = {{
\t\t# Registration may not have completed yet on the first pass.
\t\tlimit = {{ has_variable_list = cmm_list_items_{MOD_ID}__continent }}
\t\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__continent field_slot = 1 list_name = {MOD_ID}_zone_ticks }}
\t\tevery_in_list = {{
\t\t\tvariable = {MOD_ID}_zone_ticks
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_continents target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_zone_count add = 1 }}
\t\t}}
\t}}
}}

# Every land location of the ticked continents, for when the player ranks a whole
# continent without narrowing it first.
# Scope: country
{MOD_ID}_collect_zone = {{
\tevery_in_global_list = {{
\t\tvariable = {MOD_ID}_continents
\t\tevery_location_in_continent = {{
\t\t\tlimit = {{ {MOD_ID}_is_candidate = yes }}
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_candidates target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_candidate_count add = 1 }}
\t\t}}
\t}}
}}
""")
    return "".join(out)


def triggers_file(rows, split) -> str:
    out = [HEADER, f"""#
# Whether the map picker and the ranking offer this location at all.
#
# The ticked continents narrow it; with nothing ticked the whole world is on
# offer, because a picker that shows nothing until a checkbox somewhere else is
# set looks broken rather than empty. Ownership is deliberately never asked --
# the whole use is planning for ground that is not yours yet.
#
# Scope: location
{MOD_ID}_in_zone = {{
\tOR = {{
\t\tAND = {{
\t\t\tglobal_var:{MOD_ID}_zone_count = 0
\t\t\tglobal_var:{MOD_ID}_region_count = 0
\t\t}}
\t\tregion = {{ is_target_in_global_variable_list = {{ name = {MOD_ID}_regions target = this }} }}
"""]
    for key in CONTINENTS:
        out.append(f"""\t\tAND = {{
\t\t\tcontinent = continent:{key}
\t\t\tis_target_in_global_variable_list = {{ name = {MOD_ID}_continents target = continent:{key} }}
\t\t}}
""")
    out.append("\t}\n}\n")

    # "Only where it can be built today", per good. `can_build_building` is the
    # documented trigger and takes a literal building type, so the alternative --
    # walking `any_building_type` and asking what it produces -- would have needed
    # a trigger that does not exist.
    order = [good for kind in ("raw", "made") for good in split[kind]]
    by_good: dict[str, list[str]] = {}
    for method in rows:
        by_good.setdefault(method.produced, [])
        if method.building not in by_good[method.produced]:
            by_good[method.produced].append(method.building)

    out.append(f"""
# Scope: location
{MOD_ID}_can_build_something = {{
""")
    for index, good in enumerate(order, start=1):
        keyword = "if" if index == 1 else "else_if"
        out.append(f"\t{keyword} = {{ limit = {{ global_var:{MOD_ID}_good_index = {index} }} "
                   f"{MOD_ID}_can_build_{index} = yes }}\n")
    out.append("}\n")

    for index, good in enumerate(order, start=1):
        out.append(f"\n# {good}\n# Scope: location\n{MOD_ID}_can_build_{index} = {{\n\tOR = {{\n")
        for building in sorted(by_good.get(good, [])):
            out.append(f"\t\tcan_build_building = building_type:{building}\n")
        out.append("\t}\n}\n")

    # Which methods this country may actually run.
    #
    # 119 buildings in the game are unlocked by an advance with an age on it, and
    # ten production methods are unlocked separately, so `can_build_building` in
    # *country* scope -- "country checks the country scope requirements" -- is
    # what answers "is this available to me now". Without it the table happily
    # recommends a method three ages away, which is what the owner saw on beer.
    out.append("\n# Scope: country\n")
    for index, method in enumerate(rows, start=1):
        gate = UNLOCKS.get(method.key)
        extra = f"\n\thas_advance = {gate}" if gate else ""
        out.append(f"{MOD_ID}_avail_{index} = {{\n"
                   f"\tcan_build_building = building_type:{method.building}{extra}\n}}\n")

    return "".join(out)


def picker_file(split: dict[str, list[str]], rows: list[eu5data.Method]) -> str:
    """The good picker: two lists, and only one tick standing across both."""
    out = [HEADER, """#
# Two lists rather than a dropdown, and not by preference: CMF handles a dropdown
# option click through `CMM_MarkDropdownSelection_<index>` and defines exactly
# twenty of them, so the twenty-first option onwards renders, scrolls, and
# silently keeps the old selection.
#
# One answer across both lists. Ticking a second row anywhere leaves two ticks
# standing for the instant between the click and the callback; the tick that is
# not the stored answer wins and everything else is forced off, so the tick
# visibly moves to one row and stays there.
"""]

    order = [(kind, good) for kind in ("raw", "made") for good in split[kind]]
    index_of = {good: i for i, (_, good) in enumerate(order, start=1)}
    by_good_index: dict[str, list[int]] = {}
    for i, method in enumerate(rows, start=1):
        by_good_index.setdefault(method.produced, []).append(i)

    for kind in ("raw", "made"):
        goods = split[kind]
        out.append(f"""
# Scope: country
{MOD_ID}_register_good_{kind}_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = good_{kind}
\t\ttab_id = {TAB_GOODS}
\t\titem_count = {len(goods)}
\t\tis_ordered = 0
\t}}

""")
        for row, good in enumerate(goods, start=1):
            out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                       f"setting_id = good_{kind} item = {row} value = goods:{good} }}\n")
        out.append("\n")
        for row, good in enumerate(goods, start=1):
            out.append(f"\tset_variable = {{ name = {MOD_ID}__good_{kind}_i{row}_name "
                       f"value = flag:{MOD_ID}_good_{good} }}\n")
        out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = good_{kind}
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}
""")

    out.append(f"""
# Read both lists and settle on one good.
# Scope: country
{MOD_ID}_read_good = {{
\tset_variable = {{ name = {MOD_ID}_good_new value = 0 }}
\tset_variable = {{ name = {MOD_ID}_tick_count value = 0 }}
""")
    for kind in ("raw", "made"):
        out.append(f"""\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__good_{kind} field_slot = 1 list_name = {MOD_ID}_good_{kind}_ticks }}
\tevery_in_list = {{
\t\tvariable = {MOD_ID}_good_{kind}_ticks
\t\troot = {{ change_variable = {{ name = {MOD_ID}_tick_count add = 1 }} }}
""")
        for good in split[kind]:
            index = index_of[good]
            out.append(f"\t\tif = {{ limit = {{ this = goods:{good} }} root = {{ "
                       f"if = {{ limit = {{ NOT = {{ var:{MOD_ID}_good_index = {index} }} }} "
                       f"set_variable = {{ name = {MOD_ID}_good_new value = {index} }} }} }} }}\n")
        out.append("\t}\n")
    out.append(f"""
\t# A tick that is not the stored answer is the new answer. Nothing new ticked
\t# means the player unticked the old one, and the answer goes with it.
\tif = {{
\t\tlimit = {{ var:{MOD_ID}_good_new > 0 }}
\t\tset_variable = {{ name = {MOD_ID}_good_index value = var:{MOD_ID}_good_new }}
\t}}
\telse_if = {{
\t\tlimit = {{ var:{MOD_ID}_tick_count = 0 }}
\t\tset_variable = {{ name = {MOD_ID}_good_index value = 0 }}
\t}}

""")
    for good, index in ((g, index_of[g]) for _, g in order):
        keyword = "if" if index == 1 else "else_if"
        out.append(f"\t{keyword} = {{ limit = {{ var:{MOD_ID}_good_index = {index} }} "
                   f"set_global_variable = {{ name = {MOD_ID}_good value = goods:{good} }} }}\n")
    out.append("}\n")

    out.append(f"""
# Force every row but the answer off.
# Scope: country
{MOD_ID}_only_one_good = {{
""")
    for kind in ("raw", "made"):
        for row, good in enumerate(split[kind], start=1):
            out.append(f"""\tif = {{
\t\tlimit = {{ NOT = {{ var:{MOD_ID}_good_index = {index_of[good]} }} }}
\t\tcmm_set_list_data_value = {{ mod_id = {MOD_ID} setting_id = good_{kind} field_id = pick item = {row} value = 0 }}
\t}}
""")
    out.append("}\n")

    out.append(f"""
# Hide the goods this country cannot make anything of yet. A good whose every
# recipe is three ages away is a row that can only disappoint, and the owner
# named tobacco and silk as the shape of it -- both real, both made by
# plantations, and both worth hiding until the plantation is unlocked.
# Scope: country
{MOD_ID}_refresh_goods = {{
""")
    for kind in ("raw", "made"):
        for row, good in enumerate(split[kind], start=1):
            available = " ".join(f"{MOD_ID}_avail_{i} = yes" for i in by_good_index.get(good, []))
            out.append(f"""\tif = {{
\t\tlimit = {{ OR = {{ has_global_variable = {MOD_ID}_any_method {available} }} }}
\t\tcmm_show_list_item = {{ mod_id = {MOD_ID} setting_id = good_{kind} item = {row} }}
\t}}
\telse = {{
\t\tcmm_hide_list_item = {{ mod_id = {MOD_ID} setting_id = good_{kind} item = {row} }}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def values_file(rows: list[eu5data.Method], game: eu5data.Game) -> str:
    """One script value per method: what it would earn in this location.

    The weights are constants -- a method's share of the ceiling per raw material
    -- so each value is a sum of the ones the province can supply. No global
    variable is involved any more, because the method is no longer something the
    player chose; every method is scored and the best wins.
    """
    out = [HEADER, f"""#
# `RGO bonus % = {eu5data.RGO_MAX_BONUS:g} * (input amounts the province supplies) / (all input amounts)`,
# with the division done here, once per method, at generation time.
#
# The province, not the location: the game credits a raw material worked anywhere
# in the province, which is what its own tooltip says and what `rgo_bonus_filter`
# already matches on screen. Every input counts towards the denominator, produced
# goods included -- an RGO can never supply tools, but tools still carry their
# weight, which is why a method can top out well below {eu5data.RGO_MAX_BONUS:g}%.
"""]
    for index, method in enumerate(rows, start=1):
        total = method.total_input
        out.append(f"\n# {method.building} / {method.key} -> {method.produced}, "
                   f"ceiling {method.ceiling(game.raw_goods):.2f}%\n")
        out.append(f"# Scope: location\n{MOD_ID}_m{index} = {{\n\tvalue = 0\n")
        for good, amount in sorted(method.raw_inputs(game.raw_goods).items()):
            share = eu5data.RGO_MAX_BONUS * amount / total
            out.append(f"""\tif = {{
\t\tlimit = {{ province = {{ any_location_in_province = {{ raw_material = goods:{good} }} }} }}
\t\tadd = {share:.4f}
\t}}
""")
        out.append("}\n")

    out.append(f"""
# What the ranking sorts on, and what the rows print. Both read back what the
# scoring pass parked on the location and in global variables.
# Scope: location
{MOD_ID}_score = {{ value = var:{MOD_ID}_best }}
""")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"{MOD_ID}_show_bonus_{row} = {{ value = global_var:{MOD_ID}_bonus_{row} }}\n")
    out.append(f"""
{MOD_ID}_show_regions = {{ value = global_var:{MOD_ID}_zone_count }}
{MOD_ID}_show_candidates = {{ value = global_var:{MOD_ID}_candidate_count }}
{MOD_ID}_show_found = {{ value = global_var:{MOD_ID}_found }}
{MOD_ID}_show_picked = {{ value = global_var:{MOD_ID}_picked_count }}
{MOD_ID}_show_browse = {{ value = global_var:{MOD_ID}_browse_count }}
""")
    return "".join(out)


def score_file(rows: list[eu5data.Method], split: dict[str, list[str]]) -> str:
    """Finding the method, which is the thing the player should not have to do.

    One effect per good, walking the candidates once and keeping, per location,
    the best of that good's methods and which method it was. The dispatch over
    goods happens once rather than once per location, which is why it is out here
    rather than inside the loop.
    """
    order = [good for kind in ("raw", "made") for good in split[kind]]
    by_good: dict[str, list[int]] = {}
    for index, method in enumerate(rows, start=1):
        by_good.setdefault(method.produced, []).append(index)

    out = [HEADER, f"""#
# Scope: country
{MOD_ID}_score_candidates = {{
"""]
    for index, good in enumerate(order, start=1):
        keyword = "if" if index == 1 else "else_if"
        out.append(f"\t{keyword} = {{ limit = {{ var:{MOD_ID}_good_index = {index} }} "
                   f"{MOD_ID}_score_{index} = yes }}\n")
    out.append("}\n")

    for index, good in enumerate(order, start=1):
        methods_for = by_good.get(good, [])
        out.append(f"\n# {good}, made {len(methods_for)} way(s).\n"
                   f"# Scope: country\n{MOD_ID}_score_{index} = {{\n")
        out.append(f"\tevery_in_global_list = {{\n\t\tvariable = {MOD_ID}_candidates\n")
        out.append(f"\t\tset_variable = {{ name = {MOD_ID}_best value = 0 }}\n")
        out.append(f"\t\tset_variable = {{ name = {MOD_ID}_best_method value = 0 }}\n")
        for method_index in methods_for:
            out.append(f"""\t\tif = {{
\t\t\tlimit = {{
\t\t\t\tOR = {{
\t\t\t\t\thas_global_variable = {MOD_ID}_any_method
\t\t\t\t\troot = {{ {MOD_ID}_avail_{method_index} = yes }}
\t\t\t\t}}
\t\t\t}}
\t\t\tset_variable = {{ name = {MOD_ID}_try value = {MOD_ID}_m{method_index} }}
\t\t\tif = {{
\t\t\t\tlimit = {{ var:{MOD_ID}_try > var:{MOD_ID}_best }}
\t\t\t\tset_variable = {{ name = {MOD_ID}_best value = var:{MOD_ID}_try }}
\t\t\t\tset_variable = {{ name = {MOD_ID}_best_method value = {method_index} }}
\t\t\t}}
\t\t}}
""")
        out.append("\t}\n}\n")

    out.append(f"""
# Which building won a row, printed by the row itself. One branch per method,
# reached once per filled row rather than once per candidate.
# Scope: location
{MOD_ID}_store_winner = {{
""")
    for index, method in enumerate(rows, start=1):
        keyword = "if" if index == 1 else "else_if"
        out.append(f"\t{keyword} = {{ limit = {{ var:{MOD_ID}_best_method = {index} }} "
                   f"root = {{ set_global_variable = {{ name = {MOD_ID}_winner "
                   f"value = building_type:{method.building} }} }} }}\n")
    out.append("}\n")
    return "".join(out)


def rows_file() -> str:
    out = [HEADER, f"""#
# The result table, and the pass that fills it.
#
# Ranking is the engine's: `ordered_in_global_list` takes `order_by` as a script
# value and sorts highest first -- vanilla proves the direction by writing
# `multiply = -1` on the one place it wants the weakest -- and pairs `max` with
# `check_range_bounds = no` when the list may be shorter than asked for.
#
# Scope: country
{MOD_ID}_register_result_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = result
\t\ttab_id = plan
\t\titem_count = {RESULT_ROWS}
\t\tis_ordered = 0
\t}}
"""]
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                   f"setting_id = result item = {row} value = flag:row_{row} }}\n")
    out.append("}\n")

    out.append(f"""
# Scope: country
{MOD_ID}_clear_rows = {{
\tset_global_variable = {{ name = {MOD_ID}_found value = 0 }}
\tevery_in_global_list = {{
\t\tvariable = {MOD_ID}_row_provinces
\t\tremove_variable = {MOD_ID}_row_taken
\t}}
\tclear_global_variable_list = {MOD_ID}_row_provinces
""")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"\tremove_global_variable = {MOD_ID}_row_{row}\n")
        out.append(f"\tremove_global_variable = {MOD_ID}_bt_{row}\n")
        out.append(f"\tset_global_variable = {{ name = {MOD_ID}_bonus_{row} value = 0 }}\n")
    out.append("}\n")

    out.append(f"""
# Scope: country
{MOD_ID}_fill_rows = {{
\tordered_in_global_list = {{
\t\tvariable = {MOD_ID}_candidates
\t\torder_by = {MOD_ID}_score
\t\tmax = {RESULT_ROWS}
\t\tcheck_range_bounds = no
\t\t{MOD_ID}_store_row = yes
\t}}
}}

# Park one candidate in the slot its rank names, with the building that won it.
# The row a candidate lands in is chosen by an `if` chain rather than a `switch`,
# because the counter is a global and every `switch` in CMF and in the game reads
# a plain `var:`.
# Scope: location
{MOD_ID}_store_row = {{
\t# One row per province. Every location of a province scores the same -- the
\t# game credits a raw material worked anywhere in it -- so fifty rows of one
\t# province is fifty ways of saying one thing, and the owner ran out of table
\t# before he ran out of distinct answers.
\tif = {{
\t\tlimit = {{ province = {{ NOT = {{ has_variable = {MOD_ID}_row_taken }} }} }}
\t\tprovince = {{
\t\t\tset_variable = {{ name = {MOD_ID}_row_taken value = 1 }}
\t\t\troot = {{ add_to_global_variable_list = {{ name = {MOD_ID}_row_provinces target = prev }} }}
\t\t}}
\t\tchange_global_variable = {{ name = {MOD_ID}_found add = 1 }}
\t\t{MOD_ID}_store_winner = yes
\t\t{MOD_ID}_store_row_at = yes
\t}}
}}

# Scope: location
{MOD_ID}_store_row_at = {{
""")
    for row in range(1, RESULT_ROWS + 1):
        keyword = "if" if row == 1 else "else_if"
        out.append(f"""\t{keyword} = {{
\t\tlimit = {{ global_var:{MOD_ID}_found = {row} }}
\t\tset_global_variable = {{ name = {MOD_ID}_row_{row} value = this }}
\t\tset_global_variable = {{ name = {MOD_ID}_bonus_{row} value = var:{MOD_ID}_best }}
\t\tset_global_variable = {{ name = {MOD_ID}_bt_{row} value = global_var:{MOD_ID}_winner }}
\t}}
""")
    out.append("}\n")

    out.append(f"""
# Rows past the last result would otherwise show the previous run's location.
# Scope: country
{MOD_ID}_trim_rows = {{
""")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"""\tif = {{
\t\tlimit = {{ global_var:{MOD_ID}_found >= {row} }}
\t\tcmm_show_list_item = {{ mod_id = {MOD_ID} setting_id = result item = {row} }}
\t}}
\telse = {{
\t\tcmm_hide_list_item = {{ mod_id = {MOD_ID} setting_id = result item = {row} }}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def guis_file(by_continent) -> str:
    """One `_on_changed` per list, and they are not optional.

    Registering a list marks the setting as having a scripted GUI, and CMM then
    draws the row only while `CMMGuiIsShown('<setting>_on_changed')`. Without one
    the whole widget is hidden, header included -- and because a list is filed
    under a group named after itself, the group header still renders, so a
    missing callback looks like an empty list rather than a missing one.
    """
    out = [HEADER, """#
# A list reaches nothing but its own `_on_changed`: bool, dropdown, numeric,
# slider and button settings auto-apply and reach `cmf_on_callback`, and a list
# reaches neither until `cmm_apply_list_change` is called here.
"""]
    for setting, after in (
        [(f"region_{c}", f"{MOD_ID}_zone_changed = yes") for c in by_continent] + [
        ("continent", f"{MOD_ID}_zone_changed = yes"),
        ("good_raw", f"{MOD_ID}_good_changed = yes"),
        ("good_made", f"{MOD_ID}_good_changed = yes"),
        ("result", ""),
    ]):
        body = f"\t\t{after}\n" if after else ""
        out.append(f"""
{MOD_ID}__{setting}_on_changed = {{
\tscope = country

\tis_shown = {{
\t\talways = yes
\t}}

\teffect = {{
\t\tcmm_apply_list_change = {{
\t\t\tsetting = {MOD_ID}__{setting}
\t\t}}
{body}\t}}
}}
""")
    return "".join(out)


def loc_file(language: str, rows: list[eu5data.Method], split: dict[str, list[str]]) -> str:
    """The generated keys, identical in every language.

    Every name in here is the game's own, reached through `$key$` substitution or
    a data function, so this file needs no translating and cannot drift from what
    the game calls things.
    """
    out = [f"l_{language}:\n"]

    for kind in ("raw", "made"):
        for good in split[kind]:
            out.append(f" {MOD_ID}_good_{good}: "
                       f'"@{good}! [ShowGoodsName(\'{good}\')]"\n')

    out.append("\n")
    for row in range(1, RESULT_ROWS + 1):
        # Square brackets in a localization value are data function syntax, so
        # every one of these is code: the location and the winning building come
        # out of global variables, the number out of a script value.
        out.append(
            f" {MOD_ID}__result_i{row}_name: "
            f'"[GetGlobalVariable(\'{MOD_ID}_row_{row}\').GetLocation.GetName] — '
            f"[GuiScope.SetRoot(GetPlayer.MakeScope).ScriptValue('{MOD_ID}_show_bonus_{row}')|2]% — "
            f'[GetGlobalVariable(\'{MOD_ID}_bt_{row}\').GetBuildingType.GetName]"\n'
        )

    return "".join(out)


def main() -> int:
    game = eu5data.load_game()
    rows = methods(game)
    split = goods_split(rows, game)

    by_continent = regions()
    write(ZONE_OUT, zone_file())
    write(REGION_OUT, region_file(by_continent))
    write(TRIGGERS_OUT, triggers_file(rows, split))
    write(PICKER_OUT, picker_file(split, rows))
    write(VALUES_OUT, values_file(rows, game))
    write(SCORE_OUT, score_file(rows, split))
    write(ROWS_OUT, rows_file())
    write(GUIS_OUT, guis_file(by_continent))
    for language in LOC_LANGUAGES:
        write(Path(str(LOC_OUT) % (language, language)), loc_file(language, rows, split))

    print(f"{sum(len(v) for v in by_continent.values())} regions in "
          f"{len(by_continent)} lists, {len(UNLOCKS)} methods gated by an advance")
    print(f"{len(rows)} methods scored, {len(split['raw'])} raw + {len(split['made'])} made goods, "
          f"{len(CONTINENTS)} continents, {RESULT_ROWS} result rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
