#!/usr/bin/env python3
"""Generate everything `where_to_produce` cannot write by hand.

Four things come out of the game's own files rather than out of a list somebody
typed, so a patch that renames a region or adds a production method is picked up
by a rebuild:

  - **The picker.** Two lists: the 47 goods an RGO can help make, and the ways
    the chosen one is made -- at most 20, relabelled per good by pointing each
    row's `_name` variable at a different key. Not a dropdown: CMF handles an
    option click through `CMM_MarkDropdownSelection_<index>` and defines twenty
    of them, so a dropdown is only clickable to its twentieth option.
  - **The region picker.** The regions of the world, grouped by continent, read
    out of the game's own `region_names_l_english.yml`. Six lists, none of them
    near CMM's fifty-item ceiling. Seventy of the seventy-seven are proved real
    by the game's own script scoping into them; the rest are printed on every
    rebuild, because a localization file can name a key the map does not define.
  - **The weights.** Choosing a method sets one global variable per raw material
    it consumes, already divided by the method's total input weight and
    multiplied by the ceiling. The bonus script value is then a plain sum, and
    the formula lives in exactly one place.
  - **The result rows.** Fifty of them, each reading back a location and a
    number the ranking pass parked in global variables.

The formula is `eu5data.Method.bonus`, verified to the digit against three
in-game tooltips at 1.3.10. See `docs/research/engine.md`.

    python3 mods/where_to_produce/tools/generate.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(REPO / "tools"))

import eu5data  # noqa: E402
import refs  # noqa: E402

MOD_ID = "bag_wtp"

# How many rows the result table has. CMF initialises list items through an
# unrolled chain of `if`s that ends at fifty, so a taller list would register its
# count and then leave the rest uninitialised -- counted, undrawn, and silent
# about it. Raising this means leaving CMM, not editing this number.
RESULT_ROWS = 50

# Raw materials a single method can want. The widest recipe in the game takes
# five, and the row tooltip names them all.
MAX_INPUTS = 5

# How tall the recipe list is: the most (building, method) pairs any one good is
# made by. Liquor is the widest at twenty, which is inside a CMM list's fifty.
MAX_RECIPES = 20

ZONE_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_zone.txt"
METHOD_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_method.txt"
ROWS_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_rows.txt"
PICKER_OUT = MOD / "in_game/common/scripted_effects/bag_wtp_generated_picker.txt"
VALUES_OUT = MOD / "in_game/common/script_values/bag_wtp_generated_values.txt"
GUIS_OUT = MOD / "in_game/common/scripted_guis/bag_wtp_generated_scripted_gui.txt"
LOC_OUT = MOD / "main_menu/localization/%s/bag_wtp_generated_l_%s.yml"
LOC_LANGUAGES = ("english", "russian")

BOM = "﻿"

# The subcontinent the open-water regions are filed under. Dropping them by name
# is what a first attempt did, and it threw out `north_atlantic_islands_region`
# -- Iceland and the Faroes, dry land the game's own script scopes into. The
# file's own grouping is the thing that actually knows.
OPEN_WATER_GROUP = "Ocean Subcontinent"

HEADER = "# Generated by mods/where_to_produce/tools/generate.py. Do not edit by hand.\n"


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(BOM + body, encoding="utf-8")


# --------------------------------------------------------------------------
# The game's regions


def regions() -> dict[str, list[str]]:
    """Continent -> region keys, read off the game's own region localization.

    The file carries the hierarchy in its comments -- continent at one indent,
    subcontinent at the next, region keys under both -- and it is the only place
    in `reference/` that knows it, because `map_data` is not in the tree. The
    keys themselves are what matters; `region:<key>` is an ordinary scope link
    the game's own script uses several hundred times.
    """
    path = refs.GAME_LOCALIZATION / "english/region_names_l_english.yml"
    lines = path.read_text(encoding="utf-8-sig").splitlines()

    out: dict[str, list[str]] = {}
    seen: set[str] = set()
    section = continent = group = None
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("l_english"):
            continue
        indent = len(line) - len(line.lstrip())
        if stripped.startswith("#"):
            name = stripped.lstrip("#").strip()
            if indent <= 1:
                section, continent, group = name, None, None
            elif indent <= 2:
                continent, group = name, None
            else:
                group = name
            continue
        match = re.match(r"^([a-z0-9_]+):", stripped)
        if not match or continent is None:
            continue
        key = match.group(1)

        # The file's own sections are not to be trusted on their own: five real
        # regions are filed under "Subcontinents" -- `hindustan_region` and
        # `north_atlantic_islands_region` among them, and the game's script scopes
        # into both -- so the suffix has to be honoured wherever it appears. What
        # the sections do settle is the other direction: a key in the Regions
        # section is a region even without the suffix, which is how `poland` gets
        # in.
        if not (key.endswith("_region") or section == "Regions"):
            # Continents and subcontinents themselves are not offered: ticking
            # "Europe" and ticking every European region would be two ways to say
            # the same thing, and one of them would silently double the walk.
            continue
        if group == OPEN_WATER_GROUP or key in seen:
            continue
        seen.add(key)
        out.setdefault(continent, []).append(key)

    over = {c: len(r) for c, r in out.items() if len(r) > RESULT_ROWS}
    if over:
        raise SystemExit(f"a continent has more regions than a CMM list holds: {over}")
    return out


def unproven(offered: set[str]) -> list[str]:
    """Offered region keys that nothing in `reference/` ever scopes into.

    These come out of a localization file, and a localization file can name a key
    the map does not define. `region:<key>` on a key that is not a region fails at
    load -- loudly, in `error.log`, which is the good kind of failure, but it is
    still worth knowing which rows are the suspects before the game says so.
    """
    used: set[str] = set()
    for root in (refs.GAME / "in_game", refs.MODS):
        for path in root.rglob("*.txt"):
            used.update(re.findall(r"region:([a-z0-9_]+)", path.read_text(
                encoding="utf-8-sig", errors="ignore")))
    return sorted(offered - used)


# --------------------------------------------------------------------------
# The methods worth offering


def methods(game: eu5data.Game) -> list[eu5data.Method]:
    """Every method that could gain something from an RGO, in picker order.

    A method with no raw-material input can never take the bonus, so offering it
    would be offering a row that is always zero.
    """
    rows = [m for m in game.methods if m.raw_inputs(game.raw_goods)]
    # By building, so a building's methods are adjacent and one scroll finds
    # them. Sorting by the good put a building's methods far apart whenever it
    # makes more than one thing, which is the case the picker is hardest for.
    return sorted(rows, key=lambda m: (m.building, m.produced, m.key))


# --------------------------------------------------------------------------
# Output


def zone_file(by_continent: dict[str, list[str]]) -> str:
    out = [HEADER, """#
# The region pickers. One list per continent, each row a region, one tick per
# row. Row labels are the game's own region keys handed to CMM as flags, so the
# names arrive translated in whatever language the player runs and nothing here
# has to carry a copy of them.
#
# Item ordinals are literals throughout: a CMM list macro pastes `item = var:x`
# verbatim and the load dies on it.
#
# Scope: country
"""]

    for continent, keys in by_continent.items():
        slug = re.sub(r"[^a-z0-9]+", "_", continent.lower()).strip("_")
        setting = f"zone_{slug}"
        out.append(f"\n{MOD_ID}_register_{setting} = {{\n")
        out.append(f"\tcmm_register_settings_list = {{\n")
        out.append(f"\t\tmod_id = {MOD_ID}\n\t\tsetting_id = {setting}\n")
        # `is_ordered` is not optional. CMF declares it, and a CMM macro called
        # without an argument CMF declares dies silently and takes the rest of the
        # effect with it -- which is how the first build registered no lists at
        # all and put a tab on screen with only the dropdown on it.
        out.append(f"\t\ttab_id = plan\n\t\titem_count = {len(keys)}\n"
                   f"\t\tis_ordered = 0\n\t}}\n\n")
        for index, key in enumerate(keys, start=1):
            out.append(
                f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                f"setting_id = {setting} item = {index} value = region:{key} }}\n"
            )
        out.append("\n")
        for index, key in enumerate(keys, start=1):
            out.append(
                f"\tset_variable = {{ name = {MOD_ID}__{setting}_i{index}_name "
                f"value = flag:{key} }}\n"
            )
        out.append(f"\n\tcmm_register_list_bool_field = {{\n")
        out.append(f"\t\tmod_id = {MOD_ID}\n\t\tsetting_id = {setting}\n")
        out.append("\t\tfield_id = pick\n\t\tdefault_value = 0\n\t}\n}\n")

    out.append(f"\n# Scope: country\n{MOD_ID}_register_zone_lists = {{\n")
    for continent in by_continent:
        slug = re.sub(r"[^a-z0-9]+", "_", continent.lower()).strip("_")
        out.append(f"\t{MOD_ID}_register_zone_{slug} = yes\n")
    out.append("}\n")

    out.append(f"""
# Collect the ticked regions of every list into one global list the ranking pass
# walks. `cmm_build_list_bool_list` clears the list it writes into, so each list
# is read into its own and they are merged here rather than appended.
# Scope: country
{MOD_ID}_rebuild_zone = {{
\tclear_global_variable_list = {MOD_ID}_regions
\tset_global_variable = {{ name = {MOD_ID}_region_count value = 0 }}
""")
    for continent in by_continent:
        slug = re.sub(r"[^a-z0-9]+", "_", continent.lower()).strip("_")
        setting = f"zone_{slug}"
        out.append(f"""\tif = {{
\t\t# Registration may not have completed yet on the first pass.
\t\tlimit = {{ has_variable_list = cmm_list_items_{MOD_ID}__{setting} }}
\t\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__{setting} field_slot = 1 list_name = {MOD_ID}_zone_{slug} }}
\t\tevery_in_list = {{
\t\t\tvariable = {MOD_ID}_zone_{slug}
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_regions target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_region_count add = 1 }}
\t\t}}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def method_file(rows: list[eu5data.Method], game: eu5data.Game) -> str:
    out = [HEADER, f"""#
# What choosing a method means in script.
#
# The bonus a location gets is
#
#     RGO bonus % = {eu5data.RGO_MAX_BONUS:g} * (input amounts the province supplies) / (all input amounts)
#
# and the division is done here, once, rather than in the script value that runs
# per location. Each branch below sets one weight per raw material the method
# consumes, already worth its share of the ceiling, so the script value is a
# plain sum of the weights whose material the province has.
#
# Every input counts towards the denominator, produced goods included -- an RGO
# can never supply tools, but tools still carry their weight. That is why a
# method can top out well below {eu5data.RGO_MAX_BONUS:g}%.
#
# Scope: country
"""]

    used = sorted({g for m in rows for g in m.raw_inputs(game.raw_goods)})

    out.append(f"\n{MOD_ID}_clear_weights = {{\n")
    for good in used:
        out.append(f"\tset_global_variable = {{ name = {MOD_ID}_w_{good} value = 0 }}\n")
    out.append("}\n")

    out.append(f"""
# Read the method dropdown back and apply it. The index is whatever
# `cmm_sync_setting_alias` last copied out of CMM's map, so a branch missing
# here means the dropdown and this file disagree about how many options exist --
# which is why the fallback logs rather than doing nothing.
# Scope: country
{MOD_ID}_apply_method = {{
\t{MOD_ID}_clear_weights = yes

\t# Nothing picked is a real state -- the recipe list is empty until a good is
\t# chosen -- and a `switch` with no branch for the value it is handed is not.
\tif = {{
\t\tlimit = {{ var:{MOD_ID}_method_index > 0 }}
\tswitch = {{
\t\ttrigger = var:{MOD_ID}_method_index
""")

    for index, method in enumerate(rows, start=1):
        total = method.total_input
        out.append(f"\t\t{index} = {{\n")
        out.append(f"\t\t\tset_global_variable = {{ name = {MOD_ID}_building value = building_type:{method.building} }}\n")
        for good, amount in sorted(method.raw_inputs(game.raw_goods).items()):
            share = eu5data.RGO_MAX_BONUS * amount / total
            out.append(
                f"\t\t\tset_global_variable = {{ name = {MOD_ID}_w_{good} value = {share:.4f} }}\n"
            )
        # What the row tooltip names. Stored as scopes rather than as text so the
        # localization can print them in the player's own language.
        for slot, good in enumerate(sorted(method.raw_inputs(game.raw_goods)), start=1):
            out.append(
                f"\t\t\tset_global_variable = {{ name = {MOD_ID}_wants_{slot} value = goods:{good} }}\n"
            )
        for slot in range(len(method.raw_inputs(game.raw_goods)) + 1, MAX_INPUTS + 1):
            out.append(f"\t\t\tremove_global_variable = {MOD_ID}_wants_{slot}\n")
        out.append(f"\t\t\tset_global_variable = {{ name = {MOD_ID}_ceiling value = {method.ceiling(game.raw_goods):.4f} }}\n")
        out.append("\t\t}\n")

    out.append("\t}\n\t}\n}\n")

    out.append(f"""
# How many raw materials the chosen method wants. The row label prints it as the
# denominator, so a location is read as "three of the four it could have" rather
# than as a bare percentage.
# Scope: country
{MOD_ID}_count_wanted = {{
\tset_global_variable = {{ name = {MOD_ID}_wanted value = 0 }}
""")
    for slot in range(1, MAX_INPUTS + 1):
        out.append(f"""\tif = {{
\t\tlimit = {{ has_global_variable = {MOD_ID}_wants_{slot} }}
\t\tchange_global_variable = {{ name = {MOD_ID}_wanted add = 1 }}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def values_file(rows: list[eu5data.Method], game: eu5data.Game) -> str:
    used = sorted({g for m in rows for g in m.raw_inputs(game.raw_goods)})
    out = [HEADER, f"""#
# The number every location in the selection is ranked by.
#
# One branch per raw material any offered method consumes. The weight is zero
# unless the chosen method wants that material, so this sums to the bonus of
# whichever method is selected without knowing which one it is.
#
# The province, not the location: the game credits a raw material worked
# anywhere in the province, which is what its own tooltip says and what
# `rgo_bonus_filter` already matches on screen.
#
# Scope: location
{MOD_ID}_rgo_bonus = {{
\tvalue = 0
"""]
    for good in used:
        out.append(f"""\tif = {{
\t\tlimit = {{ province = {{ any_location_in_province = {{ raw_material = goods:{good} }} }} }}
\t\tadd = global_var:{MOD_ID}_w_{good}
\t}}
""")
    out.append("}\n")

    out.append(f"""
# How many of the chosen method's raw materials this province supplies, and how
# many it wants. The row label prints both, so a location that reaches 5% out of
# a possible 10% does not read the same as one that reaches 5% out of 5%.
# Scope: location
{MOD_ID}_matched_count = {{
\tvalue = 0
""")
    for slot in range(1, MAX_INPUTS + 1):
        out.append(f"""\tif = {{
\t\tlimit = {{
\t\t\thas_global_variable = {MOD_ID}_wants_{slot}
\t\t\tprovince = {{ any_location_in_province = {{ raw_material = global_var:{MOD_ID}_wants_{slot} }} }}
\t\t}}
\t\tadd = 1
\t}}
""")
    out.append("}\n")

    out.append(f"""
# Read the parked results back for the row labels. A localization value cannot
# reach a global variable's number directly, but it can run a script value, and
# `goods_target` already prints its readings this way.
# Scope: country
""")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"{MOD_ID}_show_bonus_{row} = {{ value = global_var:{MOD_ID}_bonus_{row} }}\n")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"{MOD_ID}_show_matched_{row} = {{ value = global_var:{MOD_ID}_matched_{row} }}\n")
    out.append(f"\n{MOD_ID}_show_wanted = {{ value = global_var:{MOD_ID}_wanted }}\n")
    out.append(f"{MOD_ID}_show_regions = {{ value = global_var:{MOD_ID}_region_count }}\n")
    out.append(f"{MOD_ID}_show_candidates = {{ value = global_var:{MOD_ID}_candidate_count }}\n")
    out.append(f"{MOD_ID}_show_found = {{ value = global_var:{MOD_ID}_found }}\n")
    out.append(f"{MOD_ID}_show_picked = {{ value = global_var:{MOD_ID}_picked_count }}\n")
    out.append(f"{MOD_ID}_show_browse = {{ value = global_var:{MOD_ID}_browse_count }}\n")
    out.append(f"{MOD_ID}_show_ceiling = {{ value = global_var:{MOD_ID}_ceiling }}\n")
    return "".join(out)


def rows_file() -> str:
    out = [HEADER, f"""#
# The result table, and the pass that fills it.
#
# Ranking is the engine's: `ordered_in_global_list` takes `order_by` as a script
# value and `position` as a rank, so nothing here sorts by hand. One block per
# row, each asking for the next best candidate; `check_range_bounds = no` is
# what keeps a selection shorter than the table from logging an error per
# missing row.
#
# Scope: country
{MOD_ID}_register_result_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = result
\t\ttab_id = plan
\t\titem_count = {RESULT_ROWS}
\t\tis_ordered = 0
\t}}
"""]
    for row in range(1, RESULT_ROWS + 1):
        out.append(
            f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
            f"setting_id = result item = {row} value = flag:row_{row} }}\n"
        )
    out.append("}\n")

    out.append(f"""
# Scope: country
{MOD_ID}_clear_rows = {{
\tset_global_variable = {{ name = {MOD_ID}_found value = 0 }}
""")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"\tremove_global_variable = {MOD_ID}_row_{row}\n")
        out.append(f"\tset_global_variable = {{ name = {MOD_ID}_bonus_{row} value = 0 }}\n")
        out.append(f"\tset_global_variable = {{ name = {MOD_ID}_matched_{row} value = 0 }}\n")
    out.append("}\n")

    out.append(f"""
# One sorted pass, and the rank is a running count rather than a `position`.
#
# `order_by` sorts highest first -- the game's own script proves it by writing
# `multiply = -1` on the one place it wants the weakest -- and `max` with
# `check_range_bounds = no` is the pairing vanilla uses when the list may be
# shorter than the number asked for.
#
# The row a candidate lands in is chosen by an `if` chain rather than a `switch`,
# because the counter is a global and every `switch` in CMF and in the game reads
# a plain `var:`. Fifty branches of a construct that certainly works beat one of a
# construct that probably does.
# Scope: country
{MOD_ID}_fill_rows = {{
\tordered_in_global_list = {{
\t\tvariable = {MOD_ID}_candidates
\t\torder_by = {MOD_ID}_rgo_bonus
\t\tmax = {RESULT_ROWS}
\t\tcheck_range_bounds = no
\t\tchange_global_variable = {{ name = {MOD_ID}_found add = 1 }}
\t\t{MOD_ID}_store_row = yes
\t}}
}}

# Park one candidate in the slot its rank names. Runs once per candidate, in the
# location's own scope, which is where both script values want to be evaluated.
# Scope: location
{MOD_ID}_store_row = {{
""")
    for row in range(1, RESULT_ROWS + 1):
        keyword = "if" if row == 1 else "else_if"
        out.append(f"""\t{keyword} = {{
\t\tlimit = {{ global_var:{MOD_ID}_found = {row} }}
\t\tset_global_variable = {{ name = {MOD_ID}_row_{row} value = this }}
\t\tset_global_variable = {{ name = {MOD_ID}_bonus_{row} value = {MOD_ID}_rgo_bonus }}
\t\tset_global_variable = {{ name = {MOD_ID}_matched_{row} value = {MOD_ID}_matched_count }}
\t}}
""")
    out.append("}\n")

    out.append(f"""
# Rows past the last result would otherwise show the previous run's location.
# Scope: country
{MOD_ID}_trim_rows = {{
""")
    for row in range(1, RESULT_ROWS + 1):
        out.append(f"""\tif = {{
\t\tlimit = {{ global_var:{MOD_ID}_found >= {row} }}
\t\tcmm_show_list_item = {{ mod_id = {MOD_ID} setting_id = result item = {row} }}
\t}}
\telse = {{
\t\tcmm_hide_list_item = {{ mod_id = {MOD_ID} setting_id = result item = {row} }}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def guis_file(by_continent: dict[str, list[str]]) -> str:
    """One `_on_changed` per list, and they are not optional.

    Registering a list marks the setting as having a scripted GUI, and CMM then
    draws the row only while `CMMGuiIsShown('<setting>_on_changed')`. Without one
    the whole widget is hidden, header included -- and because a list is filed
    under a group named after itself, the group header still renders, so a
    missing callback looks like an empty list rather than a missing one.

    They are also the only path a click on a list takes into script: bool,
    dropdown, numeric, slider and button settings auto-apply and reach
    `cmf_on_callback`, and a list reaches nothing until `cmm_apply_list_change`
    is called here.
    """
    out = [HEADER, """#
# The lists' change callbacks, one per list. See the generator's docstring for
# why a list without one of these is invisible rather than merely inert.
"""]

    for continent in by_continent:
        slug = re.sub(r"[^a-z0-9]+", "_", continent.lower()).strip("_")
        out.append(f"""
{MOD_ID}__zone_{slug}_on_changed = {{
\tscope = country

\tis_shown = {{
\t\talways = yes
\t}}

\teffect = {{
\t\tcmm_apply_list_change = {{
\t\t\tsetting = {MOD_ID}__zone_{slug}
\t\t}}
\t\t{MOD_ID}_zone_changed = yes
\t}}
}}
""")

    out.append(f"""
# Picking a good rewrites the recipe list underneath it, so the two callbacks are
# not symmetrical: the first refills, the second only reads.
{MOD_ID}__good_on_changed = {{
\tscope = country

\tis_shown = {{
\t\talways = yes
\t}}

\teffect = {{
\t\tcmm_apply_list_change = {{
\t\t\tsetting = {MOD_ID}__good
\t\t}}
\t\t{MOD_ID}_read_good = yes
\t\t{MOD_ID}_only_one_good = yes
\t\t{MOD_ID}_fill_recipes = yes
\t\t{MOD_ID}_recipe_reset = yes
\t}}
}}

{MOD_ID}__recipe_on_changed = {{
\tscope = country

\tis_shown = {{
\t\talways = yes
\t}}

\teffect = {{
\t\tcmm_apply_list_change = {{
\t\t\tsetting = {MOD_ID}__recipe
\t\t}}
\t\t{MOD_ID}_read_recipe = yes
\t\t{MOD_ID}_only_one_recipe = yes
\t\t{MOD_ID}_apply_method = yes
\t\t{MOD_ID}_count_wanted = yes
\t}}
}}
""")

    out.append(f"""
# The result table is read-only -- there is nothing to tick in it. It still needs
# a callback, because that is what makes the rows visible at all.
{MOD_ID}__result_on_changed = {{
\tscope = country

\tis_shown = {{
\t\talways = yes
\t}}

\teffect = {{
\t\tcmm_apply_list_change = {{
\t\t\tsetting = {MOD_ID}__result
\t\t}}
\t}}
}}
""")
    return "".join(out)


def picker_file(rows: list[eu5data.Method], game: eu5data.Game) -> str:
    """The two-step picker: a good, then one of the ways that good is made.

    A flat list of 218 was unusable for two reasons the game found for us. A CMM
    dropdown renders every option but only the first twenty can be clicked --
    CMF handles an option click through `CMM_MarkDropdownSelection_<index>` and
    defines exactly twenty of them, so anything past the twentieth silently keeps
    the old selection. And at about 165 pixels the control elides everything
    after the first field anyway.

    So both steps are lists, which CMF handles to fifty (`CMM_MarkListPosition_*`
    is unrolled to fifty, matching the item cap). 47 goods and at most 20 recipes
    per good both fit. The recipe rows are relabelled per good at runtime by
    pointing each row's `_name` variable at a different localization key, which is
    the same mechanism that puts the game's own region names on the region rows.
    """
    goods = sorted({m.produced for m in rows})
    by_good: dict[str, list[int]] = {}
    for index, method in enumerate(rows, start=1):
        by_good.setdefault(method.produced, []).append(index)
    for good in goods:
        by_good[good].sort(key=lambda i: (rows[i - 1].building, rows[i - 1].key))

    widest = max(len(v) for v in by_good.values())
    if widest > MAX_RECIPES:
        raise SystemExit(f"a good is made {widest} ways; the recipe list holds {MAX_RECIPES}")
    if len(goods) > RESULT_ROWS:
        raise SystemExit(f"{len(goods)} goods; a CMM list holds {RESULT_ROWS}")

    out = [HEADER, f"""#
# See the generator's `picker_file` for why neither step is a dropdown.
#
# Scope: country
{MOD_ID}_register_good_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = good
\t\ttab_id = plan
\t\titem_count = {len(goods)}
\t\tis_ordered = 0
\t}}

"""]
    for index, good in enumerate(goods, start=1):
        out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                   f"setting_id = good item = {index} value = goods:{good} }}\n")
    out.append("\n")
    for index, good in enumerate(goods, start=1):
        out.append(f"\tset_variable = {{ name = {MOD_ID}__good_i{index}_name "
                   f"value = flag:{MOD_ID}_good_{good} }}\n")
    out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = good
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}

# The recipe list is registered at its full height once and rewritten in place:
# CMM's dynamic builder only runs before the list is initialised, so a list whose
# contents change has to be born at its widest.
# Scope: country
{MOD_ID}_register_recipe_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = recipe
\t\ttab_id = plan
\t\titem_count = {MAX_RECIPES}
\t\tis_ordered = 0
\t}}

""")
    for row in range(1, MAX_RECIPES + 1):
        out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                   f"setting_id = recipe item = {row} value = flag:{MOD_ID}_row_{row} }}\n")
    out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = recipe
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}

# Which good is ticked. The ticked rows come back as the goods themselves, so
# this is a chain over the catalogue rather than over row ordinals.
# Scope: country
{MOD_ID}_read_good = {{
\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__good field_slot = 1 list_name = {MOD_ID}_good_ticks }}
\tset_variable = {{ name = {MOD_ID}_good_index value = 0 }}
\tevery_in_list = {{
\t\tvariable = {MOD_ID}_good_ticks
""")
    for index, good in enumerate(goods, start=1):
        keyword = "if" if index == 1 else "else_if"
        out.append(f"\t\t{keyword} = {{ limit = {{ this = goods:{good} }} "
                   f"root = {{ set_variable = {{ name = {MOD_ID}_good_index value = {index} }} }} }}\n")
    out.append("\t}\n}\n")

    out.append(f"""
# Fill the recipe list for whichever good is ticked: each row's label points at
# the key for one (building, method) pair, and each row remembers which method
# that is. Rows the good does not reach are hidden rather than left showing the
# previous good's.
# Scope: country
{MOD_ID}_fill_recipes = {{
\tswitch = {{
\t\ttrigger = var:{MOD_ID}_good_index
""")
    for index, good in enumerate(goods, start=1):
        out.append(f"\t\t{index} = {{ {MOD_ID}_fill_recipes_{index} = yes }}\n")
    out.append("\t}\n}\n")

    for index, good in enumerate(goods, start=1):
        recipes = by_good[good]
        out.append(f"\n# {good}: {len(recipes)} way(s) to make it.\n"
                   f"# Scope: country\n{MOD_ID}_fill_recipes_{index} = {{\n")
        out.append(f"\tset_global_variable = {{ name = {MOD_ID}_recipe_count value = {len(recipes)} }}\n")
        for row, method_index in enumerate(recipes, start=1):
            out.append(f"\tset_variable = {{ name = {MOD_ID}__recipe_i{row}_name "
                       f"value = flag:{MOD_ID}_recipe_{method_index} }}\n")
            out.append(f"\tset_global_variable = {{ name = {MOD_ID}_row_method_{row} value = {method_index} }}\n")
            out.append(f"\tcmm_show_list_item = {{ mod_id = {MOD_ID} setting_id = recipe item = {row} }}\n")
        for row in range(len(recipes) + 1, MAX_RECIPES + 1):
            out.append(f"\tcmm_hide_list_item = {{ mod_id = {MOD_ID} setting_id = recipe item = {row} }}\n")
        out.append("}\n")

    out.append(f"""
# Which recipe row is ticked, and therefore which method. The rows carry fixed
# flags, so this is twenty branches rather than one per method.
# Scope: country
{MOD_ID}_read_recipe = {{
\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__recipe field_slot = 1 list_name = {MOD_ID}_recipe_ticks }}
\tevery_in_list = {{
\t\tvariable = {MOD_ID}_recipe_ticks
""")
    for row in range(1, MAX_RECIPES + 1):
        keyword = "if" if row == 1 else "else_if"
        out.append(f"\t\t{keyword} = {{ limit = {{ this = flag:{MOD_ID}_row_{row} }} root = {{ "
                   f"set_variable = {{ name = {MOD_ID}_method_index "
                   f"value = global_var:{MOD_ID}_row_method_{row} }} "
                   f"set_variable = {{ name = {MOD_ID}_recipe_row value = {row} }} }} }}\n")
    out.append("\t}\n}\n")

    # One answer per list. Ticking a second row leaves two ticks standing for the
    # instant between the click and this; whichever is later in row order wins and
    # the rest are forced off, so the tick visibly moves to one row and stays
    # there. Deterministic, and it needs no comparison between a scope and a
    # variable holding one -- the shape that left the first `where_to_produce`
    # with six suspects and no way to choose between them.
    for setting, count, kept in (("good", len(goods), "good_index"),
                                 ("recipe", MAX_RECIPES, "recipe_row")):
        out.append(f"""
# Leave only the winning tick standing in the {setting} list.
# Scope: country
{MOD_ID}_only_one_{setting} = {{
""")
        for item in range(1, count + 1):
            out.append(f"""\tif = {{
\t\tlimit = {{ NOT = {{ var:{MOD_ID}_{kept} = {item} }} }}
\t\tcmm_set_list_data_value = {{ mod_id = {MOD_ID} setting_id = {setting} field_id = pick item = {item} value = 0 }}
\t}}
""")
        out.append("}\n")

    return "".join(out)


def loc_file(language: str, rows: list[eu5data.Method], game: eu5data.Game) -> str:
    """The generated keys, identical in every language.

    Every name in here is the game's own, reached through `$key$` substitution
    for buildings and methods and through a data function for goods, so this file
    needs no translating and cannot drift from what the game calls things.
    """
    out = [f"l_{language}:\n"]

    # The goods, for the first step of the picker.
    for good in sorted({m.produced for m in rows}):
        out.append(
            f" {MOD_ID}_good_{good}: "
            f'"@{good}! [ShowGoodsName(\'{good}\')]"\n'
        )

    out.append("\n")
    # One key per (building, method) pair, for the second. A recipe row points
    # its label variable at one of these, which is how the same twenty rows say
    # something different for each good. The building leads because a row is
    # about a fifth of the panel wide and the tail is elided.
    for index, method in enumerate(rows, start=1):
        out.append(
            f" {MOD_ID}_recipe_{index}: "
            f'"${method.building}$ — ${method.key}$"\n'
        )

    out.append("\n")
    for row in range(1, RESULT_ROWS + 1):
        # Square brackets in a localization value are data function syntax, so
        # every one of these is code: the location comes out of a global
        # variable, the two numbers out of script values.
        out.append(
            f" {MOD_ID}__result_i{row}_name: "
            f'"[GetGlobalVariable(\'{MOD_ID}_row_{row}\').GetLocation.GetName] — '
            f"[GuiScope.SetRoot(GetPlayer.MakeScope).ScriptValue('{MOD_ID}_show_bonus_{row}')|2]% "
            f"([GuiScope.SetRoot(GetPlayer.MakeScope).ScriptValue('{MOD_ID}_show_matched_{row}')|0]"
            f'/[GuiScope.SetRoot(GetPlayer.MakeScope).ScriptValue(\'{MOD_ID}_show_wanted\')|0])"\n'
        )

    return "".join(out)


def main() -> int:
    game = eu5data.load_game()
    rows = methods(game)
    by_continent = regions()

    write(ZONE_OUT, zone_file(by_continent))
    write(METHOD_OUT, method_file(rows, game))
    write(VALUES_OUT, values_file(rows, game))
    write(ROWS_OUT, rows_file())
    write(PICKER_OUT, picker_file(rows, game))
    write(GUIS_OUT, guis_file(by_continent))
    for language in LOC_LANGUAGES:
        write(Path(str(LOC_OUT) % (language, language)), loc_file(language, rows, game))

    offered = {k for keys in by_continent.values() for k in keys}
    print(f"{len(rows)} methods, {len(offered)} regions in {len(by_continent)} lists, "
          f"{RESULT_ROWS} result rows")
    suspects = unproven(offered)
    if suspects:
        print(f"     {len(offered) - len(suspects)} regions the game's own script scopes into; "
              f"unproven: {', '.join(suspects)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
