#!/usr/bin/env python3
"""Everything in `where_to_produce_v2` that comes out of the game's own files.

    python3 mods/where_to_produce_v2/tools/generate.py

or `python3 tools/refresh.py` for this and every other mod in the repository.
The owner does it from `mods.bat`.

**Today it writes the land picker and nothing else**, which is the whole of the
mod. Four files and a build stamp:

  `bag_wtp2_generated_zone.txt`          the continent list, and what a tick does
  `bag_wtp2_generated_regions.txt`       five region lists, one per continent
  `bag_wtp2_generated_triggers.txt`      `bag_wtp2_in_zone`, asked of a location
  `bag_wtp2_generated_scripted_gui.txt`  one `_on_changed` per list

**A list reaches nothing but its own `_on_changed`**, which is why the last of
those exists at all: a tick in a CMM list does not arrive at `cmf_on_callback`.

**The stamp is a probe before it is a nicety.** «Правка не работает» and «он
запускал прошлую сборку» look identical from here, and twice a report was read
as a fault in a mod whose files were already right. It is hashed from the built
files rather than from git: a commit id would move on every commit, a content
hash moves only when the mod does.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

MOD = Path(__file__).resolve().parent.parent
REPO = MOD.parent.parent
sys.path.insert(0, str(REPO / "tools"))

import refs  # noqa: E402

MOD_ID = "bag_wtp2"
TAB_ZONE = "zone"
BOM = "\ufeff"
HEADER = ("# Generated by mods/where_to_produce_v2/tools/generate.py. "
          "Do not edit by hand.\n")

# **A CMM list handles a row click to fifty and no further**: its items are
# initialised through an unrolled chain of `if`s that stops at item 50, because
# a list ordinal has to be a literal -- `item = var:x` is pasted verbatim into
# the macro and kills the load.
LIST_CAP = 50

CONTINENTS = ("europe", "asia", "africa", "america", "oceania")

ZONE_OUT = MOD / "in_game/common/scripted_effects/bag_wtp2_generated_zone.txt"
REGION_OUT = MOD / "in_game/common/scripted_effects/bag_wtp2_generated_regions.txt"
TRIGGER_OUT = MOD / "in_game/common/scripted_triggers/bag_wtp2_generated_triggers.txt"
SGUI_OUT = MOD / "in_game/common/scripted_guis/bag_wtp2_generated_scripted_gui.txt"
LOC_LANGUAGES = ("english", "russian")


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(BOM + body, encoding="utf-8")


def regions() -> dict[str, list[str]]:
    """Continent -> region keys, read off the game's own region localization.

    **Carried over from the first mod's generator, and both cautions with it.**
    The file holds the hierarchy in its comments and it is the only place in
    `reference/` that knows it, because `map_data` is not in the tree. Five real
    regions sit under "Subcontinents" and `poland` is a region without the
    `_region` suffix, so the suffix is honoured wherever it appears and the
    Regions section counts on its own; and filtering water by name would throw
    out `north_atlantic_islands_region`, which is dry land, so the file's own
    "Ocean Subcontinent" grouping does that job instead.
    """
    path = refs.GAME_LOCALIZATION / "english/region_names_l_english.yml"
    out: dict[str, list[str]] = {}
    seen: set[str] = set()
    section = continent = group = None
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("l_english"):
            continue
        indent = len(line) - len(line.lstrip())
        if stripped.startswith("#"):
            name = stripped.lstrip("#").strip()
            if indent <= 1:
                section, continent, group = name, None, None
            elif indent <= 2:
                continent, group = name, None
            else:
                group = name
            continue
        match = re.match(r"^([a-z0-9_]+):", stripped)
        if not match or continent is None:
            continue
        key = match.group(1)
        if not (key.endswith("_region") or section == "Regions"):
            continue
        if group == "Ocean Subcontinent" or key in seen:
            continue
        seen.add(key)
        out.setdefault(continent.lower(), []).append(key)
    over = {c: len(r) for c, r in out.items() if len(r) > LIST_CAP}
    if over:
        raise SystemExit(f"a continent has more regions than a CMM list holds: {over}")
    return {c: r for c, r in out.items() if c in CONTINENTS}


def zone_file() -> str:
    """The continent list: the blunt frame, ticked on the mod page."""
    out = [HEADER, "#\n# Scope: country\n"]
    out.append(f"""{MOD_ID}_register_zone_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = continent
\t\ttab_id = {TAB_ZONE}
\t\titem_count = {len(CONTINENTS)}
\t\tis_ordered = 0
\t}}

""")
    for index, key in enumerate(CONTINENTS, start=1):
        out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                   f"setting_id = continent item = {index} value = continent:{key} }}\n")
    out.append("\n")
    for index, key in enumerate(CONTINENTS, start=1):
        out.append(f"\tset_variable = {{ name = {MOD_ID}__continent_i{index}_name "
                   f"value = flag:{key} }}\n")
    out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = continent
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}

# Scope: country
{MOD_ID}_rebuild_zone = {{
\tclear_global_variable_list = {MOD_ID}_continents
\tset_global_variable = {{ name = {MOD_ID}_zone_count value = 0 }}

\tif = {{
\t\t# Registration may not have completed yet on the first pass.
\t\tlimit = {{ has_variable_list = cmm_list_items_{MOD_ID}__continent }}
\t\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__continent field_slot = 1 list_name = {MOD_ID}_zone_ticks }}
\t\tevery_in_list = {{
\t\t\tvariable = {MOD_ID}_zone_ticks
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_continents target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_zone_count add = 1 }}
\t\t}}
\t}}
}}
""")
    return "".join(out)


def region_file(by_continent: dict[str, list[str]]) -> str:
    """The regions, one list per continent, all on the zone tab.

    Ticking a whole continent paints the screen and is a blunt frame; the good
    case is one region ticked, its ground offered and everything else left
    alone, with a neighbour addable beside it. Both are here: a continent row
    and a region row do the same thing to the same frame.
    """
    out = [HEADER, "#\n# Scope: country\n"]
    for continent, keys in by_continent.items():
        out.append(f"""
{MOD_ID}_register_region_{continent}_list = {{
\tcmm_register_settings_list = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = region_{continent}
\t\ttab_id = {TAB_ZONE}
\t\titem_count = {len(keys)}
\t\tis_ordered = 0
\t}}

""")
        for index, key in enumerate(keys, start=1):
            out.append(f"\tcmm_set_list_item_value = {{ mod_id = {MOD_ID} "
                       f"setting_id = region_{continent} item = {index} value = region:{key} }}\n")
        out.append("\n")
        for index, key in enumerate(keys, start=1):
            out.append(f"\tset_variable = {{ name = {MOD_ID}__region_{continent}_i{index}_name "
                       f"value = flag:{key} }}\n")
        out.append(f"""
\tcmm_register_list_bool_field = {{
\t\tmod_id = {MOD_ID}
\t\tsetting_id = region_{continent}
\t\tfield_id = pick
\t\tdefault_value = 0
\t}}
}}
""")

    out.append(f"\n# Scope: country\n{MOD_ID}_register_region_lists = {{\n")
    for continent in by_continent:
        out.append(f"\t{MOD_ID}_register_region_{continent}_list = yes\n")
    out.append("}\n")

    out.append(f"""
# The ticked regions, gathered beside the ticked continents. Both narrow the
# same frame; a region is simply the finer of the two.
# Scope: country
{MOD_ID}_rebuild_regions = {{
\tclear_global_variable_list = {MOD_ID}_regions
\tset_global_variable = {{ name = {MOD_ID}_region_count value = 0 }}
""")
    for continent in by_continent:
        out.append(f"""\tif = {{
\t\tlimit = {{ has_variable_list = cmm_list_items_{MOD_ID}__region_{continent} }}
\t\tcmm_build_list_bool_list = {{ setting = {MOD_ID}__region_{continent} field_slot = 1 list_name = {MOD_ID}_region_{continent}_ticks }}
\t\tevery_in_list = {{
\t\t\tvariable = {MOD_ID}_region_{continent}_ticks
\t\t\tadd_to_global_variable_list = {{ name = {MOD_ID}_regions target = this }}
\t\t\tchange_global_variable = {{ name = {MOD_ID}_region_count add = 1 }}
\t\t}}
\t}}
""")
    out.append("}\n")
    return "".join(out)


def trigger_file() -> str:
    """`bag_wtp2_in_zone`: is this location inside the frame at all.

    **Nothing is written onto a location in advance.** A location's continent
    and region are plain triggers, so the question is asked where it matters
    rather than being painted over a continent's worth of locations whenever a
    tick moves.

    **Nothing ticked means the whole world**, which is what makes the mod usable
    before the player has touched the zone tab at all.
    """
    out = [HEADER, "#\n# Scope: location\n"]
    out.append(f"""{MOD_ID}_in_zone = {{
\tOR = {{
\t\tAND = {{
\t\t\tglobal_var:{MOD_ID}_zone_count = 0
\t\t\tglobal_var:{MOD_ID}_region_count = 0
\t\t}}
\t\tregion = {{ is_target_in_global_variable_list = {{ name = {MOD_ID}_regions target = this }} }}
""")
    for key in CONTINENTS:
        out.append(f"""\t\tAND = {{
\t\t\tcontinent = continent:{key}
\t\t\tis_target_in_global_variable_list = {{ name = {MOD_ID}_continents target = continent:{key} }}
\t\t}}
""")
    out.append("\t}\n}\n")
    return "".join(out)


def sgui_file(by_continent: dict[str, list[str]]) -> str:
    """One `_on_changed` per list, and without them a list is invisible.

    A CMM list does not reach `cmf_on_callback`: the only thing a tick arrives
    at is a scripted GUI named `<mod>__<setting>_on_changed`. `cmm_apply_list_change`
    is what writes the tick back into the list's own storage; everything after
    it is the mod's own business.
    """
    out = [HEADER, "\n"]
    for setting in ["continent"] + [f"region_{c}" for c in by_continent]:
        out.append(f"""{MOD_ID}__{setting}_on_changed = {{
\tscope = country

\tis_shown = {{
\t\talways = yes
\t}}

\teffect = {{
\t\tcmm_apply_list_change = {{
\t\t\tsetting = {MOD_ID}__{setting}
\t\t}}
\t\t{MOD_ID}_zone_changed = yes
\t}}
}}

""")
    return "".join(out)


def main() -> int:
    by_continent = regions()
    write(ZONE_OUT, zone_file())
    write(REGION_OUT, region_file(by_continent))
    write(TRIGGER_OUT, trigger_file())
    write(SGUI_OUT, sgui_file(by_continent))

    # The stamp's own files are written after the hash is taken, so it cannot
    # hash itself.
    stamped = sorted(
        q for q in list((MOD / "in_game").rglob("*"))
        + list((MOD / "main_menu").rglob("*"))
        if q.is_file() and q.suffix in (".txt", ".gui", ".yml")
        and not q.name.startswith(f"{MOD_ID}_build"))
    digest = hashlib.sha256()
    for q in stamped:
        digest.update(q.relative_to(MOD).as_posix().encode())
        digest.update(q.read_bytes())
    stamp = digest.hexdigest()[:6]
    for language in LOC_LANGUAGES:
        write(MOD / f"main_menu/localization/{language}/{MOD_ID}_build_l_{language}.yml",
              f"l_{language}:\n {MOD_ID}_build: \"{stamp}\"\n")

    print(f"build {stamp}, hashed from {len(stamped)} files")
    print(f"{sum(len(v) for v in by_continent.values())} regions in "
          f"{len(by_continent)} lists, {len(CONTINENTS)} continents")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
