#!/usr/bin/env python3
"""Rebuild `glorpui_hints` from Glorp UI, and refuse to write it broken.

Two things live in this mod, and they are rebuilt on different occasions:

* **Glorp UI's hint text** is its own English file with the opener replaced,
  once per language, so a Glorp UI update that adds hints is picked up in all
  eleven languages without anyone noticing it happened. Regenerated every run.
* **The extra hint lists** are compiled out of the *game's* `common/` tree —
  laws, static modifiers, religious aspects, employment systems and the rest —
  which is large, so they are committed as generated files and rebuilt only when
  asked:

      python3 mods/glorpui_hints/tools/generate.py --game-files reference/game

What runs unconditionally is the part that catches the update this mod is most
likely to be broken by. The mod **overrides Glorp UI's own override** of
`SocietalValueCountryLeft_tooltip` / `SocietalValueCountryRight_tooltip`, and it
re-emits Glorp UI's list inside it. If Glorp UI restructures those templates,
nothing errors at load: the player simply gets our older copy of Glorp UI's list
and never sees whatever Glorp UI added. So the checks below compare the two
files every run and fail naming the difference.

    python3 mods/glorpui_hints/tools/generate.py
    python3 mods/glorpui_hints/tools/generate.py --check    # write nothing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
MOD = TOOLS.parent
sys.path.insert(0, str(TOOLS))
sys.path.insert(0, str(MOD.parent.parent / "tools"))

import refs  # noqa: E402
import languages as svx_languages  # noqa: E402
import translate_hints  # noqa: E402

EXTRA_GUI = MOD / "in_game/gui/svx_extra_societal_value_hints.gui"
UNLOCK_GATE = MOD / "in_game/common/customizable_localization/svx_unlock_gate.txt"
EXTRA_CUSTOM = MOD / "in_game/common/customizable_localization/svx_extra_hint_loc.txt"
EXTRA_VALUES = MOD / "in_game/common/script_values/svx_extra_hint_script_values.txt"

# Glorp UI's hints are shipped in every language including English, where the
# render is byte-identical to Glorp UI's own file — which is checked, because
# that identity is what proves the opener parse loses nothing. English is
# shipped rather than left to Glorp UI so that all eleven folders carry exactly
# the same key set: `tools/check_cmm.py` compares them against each other, and a
# folder short of a key is the fault this whole mod exists to repair.
SHIP_GLORP_HINTS = list(svx_languages.LANGUAGES)


def hints_path(language: str) -> Path:
    return (MOD / "main_menu/localization" / language
            / translate_hints.output_name(language))


def extra_path(language: str) -> Path:
    return (MOD / "main_menu/localization" / language
            / ("svx_extra_hints_l_%s.yml" % language))


def fixes_path(language: str) -> Path:
    return (MOD / "main_menu/localization" / language
            / ("svx_glorpui_fixes_l_%s.yml" % language))


def render_fixes(language: str) -> str:
    """Glorp UI's own keys this mod repairs in one language, and only there."""
    out = [HEADER,
           "# Glorp UI's own interface keys, repaired. Only the languages whose",
           "# text is actually broken get a file: overriding a translation that",
           "# is fine would pin it against a Glorp UI update for no reason.",
           "l_%s:" % language]
    for key, text in svx_languages.GLORP_UI_FIXES[language].items():
        out.append(' %s: "%s"' % (key, text))
    return "\n".join(out) + "\n"


def menu_path(language: str) -> Path:
    return (MOD / "main_menu/localization" / language
            / ("svx_menu_l_%s.yml" % language))


GLORP_HINTS_GUI = "in_game/gui/glorpUI_generated_societal_value_hints.gui"
GLORP_HINTS_VALUES = (
    "in_game/common/script_values/glorpui_generated_societal_value_hint_script_values.txt")
GLORP_HINTS_EN = ("main_menu/localization/english/"
                  + translate_hints.SOURCE_NAME)

# One TooltipScrolledStringPairList, reduced to what it actually does: which
# script value gates it, what title it carries, which body key it prints.
ENTRY_RE = re.compile(
    r"ScriptValue\('(?P<value>\w+)'\).*?"
    r'text = "(?P<title>[A-Z_]+)".*?'
    r"Localize\('(?P<body>\w+)'\)",
    re.S)
TEMPLATE_RE = re.compile(r"^template (\w+) \{", re.M)
LOC_KEY_RE = re.compile(r"^ (\w+):", re.M)
CUSTOM_RE = re.compile(r"^(\w+) = \{$", re.M)
SCRIPT_VALUE_RE = re.compile(r"^(\w+) = \{$", re.M)
PLAYER_CUSTOM_RE = re.compile(r"\[Player\.Custom\('(\w+)'\)\]")

HEADER = ("# Auto-generated by mods/glorpui_hints/tools/generate.py from the EU5 "
          "game files. Do not edit by hand.")


def entries(text: str) -> list[tuple[str, str, str, str]]:
    """(template, gating script value, title key, body key), in file order."""
    found = []
    for match in ENTRY_RE.finditer(text):
        template = "?"
        for candidate in TEMPLATE_RE.finditer(text[:match.start()]):
            template = candidate.group(1)
        found.append((template, match.group("value"),
                      match.group("title"), match.group("body")))
    return found


def check_glorp_list_is_current(problems: list[str], glorp: Path) -> None:
    """Our re-emission of Glorp UI's list must still be Glorp UI's list.

    Compared as an ordered sequence rather than as text: the mod interleaves two
    lists of its own between Glorp UI's entries, so the file cannot match, but
    Glorp UI's entries must appear in the same order and say the same thing.
    """
    theirs = entries((glorp / GLORP_HINTS_GUI).read_text(encoding="utf-8-sig"))
    ours = [entry for entry in entries(EXTRA_GUI.read_text(encoding="utf-8-sig"))
            if entry[1].startswith("glorpui_svh_visible_")]
    if ours == theirs:
        return
    theirs_set, ours_set = set(theirs), set(ours)
    for entry in theirs:
        if entry not in ours_set:
            problems.append(
                "Glorp UI now lists %s (%s) in %s and this mod does not — "
                "rebuild with --game-files" % (entry[3], entry[1], entry[0]))
    for entry in ours:
        if entry not in theirs_set:
            problems.append(
                "this mod re-emits %s (%s) in %s and Glorp UI no longer does"
                % (entry[3], entry[1], entry[0]))
    if not problems:
        problems.append("Glorp UI's hint entries are the same but in a "
                        "different order — rebuild with --game-files")


def check_english_is_glorp_uis_own(problems: list[str], glorp: Path) -> None:
    """Rendering English must give Glorp UI's file back, character for character.

    This is the proof that splitting a hint into opener, reference and number
    loses nothing: English's openers are Glorp UI's own English, so a lossless
    parse round-trips. If Glorp UI writes a hint the parse mangles rather than
    rejects, this is what notices — the ten other languages have no original to
    be compared against.
    """
    source = glorp / GLORP_HINTS_EN
    # Ungated: a held-back hint is deliberately not what Glorp UI writes, and
    # what is being checked here is that the *parse* loses nothing.
    ours, _, _ = translate_hints.render(source, "english")
    # Two header lines are this tool's; everything after the `l_english:` line
    # must match Glorp UI's file exactly.
    mine = ours.split("\n")[2:]
    theirs = source.read_text(encoding="utf-8-sig").split("\n")[1:]
    if mine == theirs:
        return
    for line_a, line_b in zip(mine, theirs):
        if line_a != line_b:
            problems.append("English render differs from Glorp UI's own file, "
                            "so the opener parse is lossy:\n       ours:   %s\n"
                            "       theirs: %s" % (line_a[:160], line_b[:160]))
            return
    problems.append("English render differs from Glorp UI's own file in length")


ADVANCE_BLOCK_RE = re.compile(r'([A-Za-z_][A-Za-z_0-9]*)\s*=\s*\{|[{}]')
UNLOCKS_RE = re.compile(r'unlock_estate_privilege\s*=\s*([a-z_0-9]+)')
PRIVILEGE_HINT_RE = re.compile(
    r'^ (GLORP_UI_SVH_\w+): "@hint! [^"]*#TOOLTIP:ESTATE_PRIVILEGE,(\w+) ', re.M)


def privileges_locked_behind_an_advance() -> dict[str, str]:
    """privilege -> the advance whose `unlock_estate_privilege` opens it.

    Glorp UI's own filter, `glorpui_svh_privilege_takeable`, reads a privilege's
    `potential` and `allow` and nothing else. Ten vanilla privileges are locked
    from the other side instead — by an advance — and their own `potential` is
    empty, so they sail through the filter and get recommended to a country that
    cannot take them. Read out of the advances rather than listed, so a patch
    that locks an eleventh is picked up by a rebuild.
    """
    locked: dict[str, str] = {}
    root = refs.GAME_COMMON / "advances"
    if not root.is_dir():
        return locked
    for path in sorted(root.rglob("*.txt")):
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        depth, name, start = 0, None, None
        for match in ADVANCE_BLOCK_RE.finditer(text):
            token = match.group(0)
            if token.endswith("{"):
                if depth == 0 and match.group(1):
                    name, start = match.group(1), match.end()
                depth += 1
            elif token == "}":
                depth -= 1
                if depth == 0 and name:
                    for privilege in UNLOCKS_RE.findall(text[start:match.start()]):
                        locked[privilege] = name
                    name = None
    return locked


def unlock_gates(glorp: Path) -> dict[str, tuple[str, str]]:
    """Glorp UI hint key -> (privilege, advance), for hints that must wait."""
    locked = privileges_locked_behind_an_advance()
    source = (glorp / GLORP_HINTS_EN).read_text(encoding="utf-8-sig")
    return {key: (privilege, locked[privilege])
            for key, privilege in PRIVILEGE_HINT_RE.findall(source)
            if privilege in locked}


def render_unlock_gate(gates: dict[str, tuple[str, str]]) -> str:
    """The customizable localization each gated hint key dispatches to."""
    out = [HEADER,
           "# Glorp UI recommends a privilege its own filter thinks is takeable.",
           "# These are the ones an advance locks from the other side: the",
           "# privilege's own `potential` is empty, so `glorpui_svh_privilege_takeable`",
           "# lets it through. The list is scanned out of common/advances rather",
           "# than written down, so a patch that locks another one is picked up.",
           "#",
           "# The hint's own localization key is rewritten to print",
           "# [Player.Custom('svx_unlock_<key>')] and the words moved to",
           "# SVX_UNLOCK_<key>, because a customizable_localization cannot be",
           "# overridden — the first definition read wins and a later duplicate is",
           "# dropped with `gamedatabase.h: Duplicated key ... will not be created",
           "# from file`. Localization keys, on the other hand, do override, and",
           "# this mod rewrites every one of Glorp UI's already.",
           ""]
    for key, (privilege, advance) in sorted(gates.items()):
        out += ["# %s, locked by %s" % (privilege, advance),
                "%s = {" % translate_hints.gate_key(key),
                "\ttype = country",
                "\ttext = {",
                "\t\ttrigger = { has_advance = %s }" % advance,
                "\t\tlocalization_key = %s" % translate_hints.line_key(key),
                "\t}",
                "\ttext = {",
                "\t\tlocalization_key = empty_text",
                "\t}",
                "}",
                ""]
    return "\n".join(out)


def game_concept_keys() -> set[str]:
    """Every `game_concept_*` key the game defines, from its own localization."""
    keys: set[str] = set()
    root = refs.GAME / "main_menu/localization"
    for path in root.rglob("*.yml"):
        keys |= set(re.findall(r"^ (game_concept_\w+):", path.read_text(
            encoding="utf-8-sig", errors="replace"), re.M))
    return keys


def check_catalog_concepts_exist(problems: list[str]) -> None:
    """`[religious_aspect|e]` only renders because the game defines the concept.

    The fourteen category nouns are not translated by this mod — they are game
    concepts, which is what makes ten extra languages cost nothing and what
    makes the mod use the game's own word. The price is that a concept the game
    renames turns into a raw token on screen in every language at once, and
    nothing would error. So every id is checked against the game's own
    localization on every run.
    """
    defined = game_concept_keys()
    if not defined:
        problems.append("no game_concept_* keys under reference/game — "
                        "cannot check the catalogue concepts")
        return
    for source_type, concept in sorted(svx_languages.CATALOG_CONCEPTS.items()):
        if "game_concept_%s" % concept not in defined:
            problems.append("languages.py: the game defines no concept %s, "
                            "used for %s" % (concept, source_type))


def check_references_resolve(problems: list[str], glorp: Path,
                             language: str, hints: str) -> None:
    """Every name the `.gui` reaches for is defined by us or by Glorp UI.

    A `.gui` asking for a script value or a loc key that nothing defines does not
    fail to load; it prints zero, or the raw key, which is exactly the fault this
    mod exists to repair. Run per language, because a body key missing in one
    language is exactly the bug this mod was written to fix.
    """
    gui = EXTRA_GUI.read_text(encoding="utf-8-sig")
    defined_values = set(SCRIPT_VALUE_RE.findall(
        EXTRA_VALUES.read_text(encoding="utf-8-sig")))
    defined_values |= set(SCRIPT_VALUE_RE.findall(
        (glorp / GLORP_HINTS_VALUES).read_text(encoding="utf-8-sig")))
    loc = extra_path(language).read_text(encoding="utf-8-sig")
    defined_keys = set(LOC_KEY_RE.findall(loc))
    defined_keys |= set(LOC_KEY_RE.findall(hints))
    defined_keys |= set(LOC_KEY_RE.findall(
        menu_path(language).read_text(encoding="utf-8-sig")))

    for _, value, _, body in entries(gui):
        if value not in defined_values:
            problems.append("%s: no script value %s" % (EXTRA_GUI.name, value))
        if body not in defined_keys:
            problems.append("%s: no localization key %s in %s"
                            % (EXTRA_GUI.name, body, language))
    for title in {entry[2] for entry in entries(gui)}:
        # The two titles this mod adds are its own; the vanilla ones are not.
        if title.startswith("SVX_") and title not in defined_keys:
            problems.append("%s: no localization key %s in %s"
                            % (EXTRA_GUI.name, title, language))

    # And every gated line the localization prints has a rule behind it —
    # the availability gates in one file, the advance locks in the other.
    declared = set(CUSTOM_RE.findall(EXTRA_CUSTOM.read_text(encoding="utf-8-sig")))
    declared |= set(CUSTOM_RE.findall(UNLOCK_GATE.read_text(encoding="utf-8-sig")))
    used = set(PLAYER_CUSTOM_RE.findall(loc)) | set(PLAYER_CUSTOM_RE.findall(hints))
    # Glorp UI's own body keys concatenate Glorp UI's own rules; only the names
    # this mod puts into the game's namespace are this mod's to declare.
    for name in sorted({n for n in used if n.startswith("svx_")} - declared):
        problems.append("%s: no customizable localization %s"
                        % (extra_path(language).name, name))
    for name in sorted(declared - used):
        problems.append("%s: %s is declared and never printed in %s"
                        % (EXTRA_CUSTOM.name, name, language))
    for key in sorted({m.group(1) for m in re.finditer(
            r"localization_key = (\w+)",
            EXTRA_CUSTOM.read_text(encoding="utf-8-sig")
            + UNLOCK_GATE.read_text(encoding="utf-8-sig"))}):
        if key != "empty_text" and key not in defined_keys:
            problems.append("%s: no localization key %s in %s"
                            % (EXTRA_CUSTOM.name, key, language))


def check_localization_conventions(problems: list[str], language: str,
                                   files: list[tuple[Path, str]]) -> None:
    """A BOM, one leading space per key, and brackets that close.

    All three are silent in game: a file with no BOM is read as some other
    encoding and its text arrives as mojibake, a key without its leading space
    is not a key at all, and an unbalanced bracket renders as `ERROR:`.
    """
    for path, text in files:
        if not path.read_bytes().startswith(b"\xef\xbb\xbf"):
            problems.append("%s: no UTF-8 BOM" % path.name)
        header = [line for line in text.splitlines() if line.strip().startswith("l_")]
        if header != ["l_%s:" % language]:
            problems.append("%s: header is %r, want ['l_%s:']"
                            % (path.name, header, language))
        for number, line in enumerate(text.splitlines(), 1):
            if (not line.strip() or line.lstrip().startswith("#")
                    or line.strip() == "l_%s:" % language):
                continue
            if not re.match(r'^ \w+: ".*"$', line):
                problems.append("%s:%d: not ` KEY: \"value\"`" % (path.name, number))
                continue
            value = line.split(":", 1)[1]
            if value.count("[") != value.count("]"):
                problems.append("%s:%d: brackets do not balance"
                                % (path.name, number))


def check_languages_are_in_step(problems: list[str]) -> None:
    """Every language defines the same keys, and none of them is empty.

    A key defined in one language and missing in another is the bug this mod
    exists to fix, one folder further along.
    """
    per_language = {}
    for language in svx_languages.LANGUAGES:
        keys = set()
        for path in (extra_path(language), menu_path(language),
                     hints_path(language)):
            keys |= set(LOC_KEY_RE.findall(path.read_text(encoding="utf-8-sig")))
        per_language[language] = keys
    reference_language = "russian"
    expected = per_language[reference_language]
    for language, keys in per_language.items():
        missing, extra = expected - keys, keys - expected
        for key in sorted(missing)[:5]:
            problems.append("%s is missing %s, which %s defines"
                            % (language, key, reference_language))
        for key in sorted(extra)[:5]:
            problems.append("%s defines %s, which %s does not"
                            % (language, key, reference_language))


def known_triggers() -> set[str]:
    """Every name a trigger clause may legitimately start with.

    Three sources, and all three are needed:

    * the engine's own dump, which is the authority on named triggers;
    * the game's `scripted_triggers/`, for things like
      `game_has_missions_enabled` that the dump does not know about;
    * **every name the game itself writes in the same position** anywhere in
      its `common/` tree. Not everything valid is a named trigger:
      `religion = religion:catholic` and `culture = culture:low_frankish` are
      scope comparisons, appear in the dump nowhere, and are written 598 and
      1 418 times by the game. Without this third source the check reports them
      and gets ignored, which is worse than not checking.

    What survives all three is a name nothing in the game has ever written —
    which is what `country_religion` was, in 492 gates.
    """
    names = set(re.findall(
        r"^## (\w+)", (refs.GAME / "docs/triggers.log").read_text(
            encoding="utf-8", errors="replace"), re.M))
    scripted = refs.GAME_COMMON / "scripted_triggers"
    if scripted.is_dir():
        for path in scripted.glob("*.txt"):
            names |= set(re.findall(r"^(\w+)\s*=\s*\{", path.read_text(
                encoding="utf-8-sig", errors="replace"), re.M))
    for path in refs.GAME_COMMON.rglob("*.txt"):
        names |= set(TRIGGER_CALL.findall(path.read_text(
            encoding="utf-8-sig", errors="replace")))
    return names


# A `name = ` at the start of a trigger clause. Values, targets and the right
# hand side of a comparison are not names being called.
TRIGGER_CALL = re.compile(r"(?:^|[{\s])([a-z_][a-z_0-9]*)\s*(?:=|<|>|<=|>=)")
# Logic and control words, which are the engine's own and not in the dump.
TRIGGER_KEYWORDS = {
    "and", "or", "not", "nor", "nand", "if", "else", "else_if", "limit",
    "trigger_if", "trigger_else", "trigger_else_if", "custom_tooltip",
    "custom_description", "hidden_trigger", "value", "add", "subtract",
    "multiply", "divide", "min", "max", "desc", "type", "text",
    "localization_key", "trigger", "scale", "count", "percent", "amount",
}


def trigger_blocks(text: str) -> str:
    """Just the insides of every `trigger = { ... }`, joined.

    The rest of the file is definition names and `localization_key = X`, and
    reading those as trigger calls reports every gate in the mod as unknown.
    """
    out = []
    for match in re.finditer(r"\btrigger\s*=\s*\{", text):
        depth = 0
        for index in range(match.end() - 1, len(text)):
            if text[index] == "{":
                depth += 1
            elif text[index] == "}":
                depth -= 1
                if depth == 0:
                    out.append(text[match.end():index])
                    break
    return "\n".join(out)


def check_triggers_exist(problems: list[str]) -> None:
    """Every trigger the gates call is one the engine or the game defines.

    A mistyped trigger name is a load error, not a quiet nothing — but it is a
    load error in the *player's* game, found by them, a round trip away. The
    names come out of the shipped files and the engine's own dump, so checking
    them costs nothing and closes the one way this file can be wrong by a
    keystroke.
    """
    known = known_triggers()
    if not known:
        problems.append("no triggers.log in reference/ — cannot check trigger names")
        return
    seen: dict[str, int] = {}
    for name in TRIGGER_CALL.findall(trigger_blocks(
            EXTRA_CUSTOM.read_text(encoding="utf-8-sig")
            + UNLOCK_GATE.read_text(encoding="utf-8-sig"))):
        if name in TRIGGER_KEYWORDS or name in known:
            continue
        seen[name] = seen.get(name, 0) + 1
    for name, count in sorted(seen.items()):
        problems.append("%s: no trigger named %s (%d call%s)"
                        % (EXTRA_CUSTOM.name, name, count, "" if count == 1 else "s"))


# One entry of a TooltipScrolledStringPairList: everything between `@hint!` and
# the colon that splits the pair. `(?:(?!@hint!).)` rather than `.` because a
# body key is one long line of many entries, and a plain non-greedy match starts
# at the *first* `@hint!` and swallows every entry up to the first colon — which
# made the first version of this check pass on a label it was written to catch.
HINT_LABEL = re.compile(r"@hint!((?:(?!@hint!).)*?):\s*#color_green")
# What is markup or a reference rather than something a player reads.
NOT_TEXT = re.compile(r"\$[^$]*\$|\[[^\]]*\]|#[A-Za-z_!]+|#!|\\n")
# A game concept link, which is the one reference that may stand as a label on
# its own — see check_hints_have_labels.
CONCEPT_TOKEN = re.compile(r"\[(\w+)\|[eE]\]")


def check_hints_have_labels(problems: list[str], language: str) -> None:
    """Every hint line says something before its number.

    A line whose whole label is `$SOME_KEY$` renders as a bare value with no
    text when that reference does not resolve, and nothing errors. It happened:
    `$STATIC_MODIFIER_NAME_parliament_outside_capital$` came out blank on screen
    while `$STATIC_MODIFIER_NAME_is_bankrupt$` two lines away came out fine.

    So the rule is not "references are banned" — the catalogue lines reference
    `$building_type$` and always have — but "a label must carry text that is
    certain to resolve". Literal text always is. A **game concept token** is the
    one reference that also is: `[religious_aspect|e]` reads
    `game_concept_religious_aspect`, the game defines it in every one of its
    localization folders, and `check_catalog_concepts_exist` verifies each id
    this mod uses against the game's own files on every run. That is what lets
    the fourteen category nouns go untranslated in eleven languages.
    """
    text = extra_path(language).read_text(encoding="utf-8-sig")
    defined = game_concept_keys()
    for label in HINT_LABEL.findall(text):
        if NOT_TEXT.sub("", label).strip():
            continue
        concepts = CONCEPT_TOKEN.findall(label)
        if concepts and all("game_concept_%s" % name in defined
                            for name in concepts):
            continue
        problems.append("%s: a hint label is nothing but markup and references"
                        " — %r would render blank"
                        % (extra_path(language).name, label.strip()))
        return


def rebuild_extra(game_files: Path) -> int:
    """Re-scan the game and rewrite the generated files, in every language."""
    # Beside the tool, not in the repository root: a crashed run used to leave
    # it where the next `git add -A` would sweep it into a commit.
    findings = TOOLS / "sv_findings.json"
    for command in (
            [sys.executable, str(TOOLS / "scan_sources.py"), str(game_files),
             "--json", str(findings)],
            [sys.executable, str(TOOLS / "generate_extra.py"),
             "--findings", str(findings), "--game-files", str(game_files),
             "--out", str(MOD)]):
        done = subprocess.run(command, capture_output=True, text=True)
        for line in (done.stdout + done.stderr).strip().splitlines():
            print("     %s" % line)
        if done.returncode != 0:
            return done.returncode
    findings.unlink(missing_ok=True)
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--game-files", type=Path,
                        help="unpacked EU5 game files, to rebuild the extra "
                             "hint lists; without it they are only checked")
    parser.add_argument("--check", action="store_true",
                        help="report, write nothing")
    args = parser.parse_args(argv[1:])

    glorp = refs.known("glorp_ui")

    if args.game_files:
        code = rebuild_extra(args.game_files)
        if code:
            return code

    gates = unlock_gates(glorp)
    if not args.check:
        UNLOCK_GATE.parent.mkdir(parents=True, exist_ok=True)
        UNLOCK_GATE.write_text(render_unlock_gate(gates), encoding="utf-8-sig",
                               newline="\n")

    if not args.check:
        for language in svx_languages.GLORP_UI_FIXES:
            fixes_path(language).parent.mkdir(parents=True, exist_ok=True)
            fixes_path(language).write_text(render_fixes(language),
                                            encoding="utf-8-sig", newline="\n")

    rendered: dict[str, str] = {}
    gated = {key: advance for key, (_, advance) in gates.items()}
    for language in svx_languages.LANGUAGES:
        try:
            text, translated, bodies = translate_hints.render(
                glorp / GLORP_HINTS_EN, language, gated)
        except translate_hints.Unrecognised as exc:
            print("Glorp UI writes a hint this mod cannot translate. Add the "
                  "opener to languages.py:\n  %s" % exc, file=sys.stderr)
            return 1
        rendered[language] = text
        if not args.check:
            hints_path(language).parent.mkdir(parents=True, exist_ok=True)
            hints_path(language).write_text(text, encoding="utf-8-sig",
                                            newline="\n")
    if not args.check:
        print("wrote %d localization folders under %s"
              % (len(svx_languages.LANGUAGES),
                 (MOD / "main_menu/localization").relative_to(refs.REPO)))
    print("%d hints translated into %d languages, %d body keys copied from Glorp UI"
          % (translated, len(SHIP_GLORP_HINTS), bodies))
    print("%d hints held back until the advance that unlocks the privilege: %s"
          % (len(gates),
             ", ".join(sorted({privilege for privilege, _ in gates.values()}))))
    print("%d of Glorp UI's own keys repaired, in %s"
          % (sum(len(v) for v in svx_languages.GLORP_UI_FIXES.values()),
             ", ".join(sorted(svx_languages.GLORP_UI_FIXES))))

    problems: list[str] = []
    check_glorp_list_is_current(problems, glorp)
    check_english_is_glorp_uis_own(problems, glorp)
    check_catalog_concepts_exist(problems)
    check_languages_are_in_step(problems)
    check_triggers_exist(problems)
    for language in svx_languages.LANGUAGES:
        check_references_resolve(problems, glorp, language, rendered[language])
        paths = [extra_path(language), menu_path(language), hints_path(language)]
        if language in svx_languages.GLORP_UI_FIXES:
            paths.append(fixes_path(language))
        check_localization_conventions(problems, language, [
            (path, path.read_text(encoding="utf-8-sig")) for path in paths])
        check_hints_have_labels(problems, language)
    if problems:
        print()
        for problem in problems:
            print("     %s" % problem, file=sys.stderr)
        return 1

    gui_entries = entries(EXTRA_GUI.read_text(encoding="utf-8-sig"))
    gated = len(CUSTOM_RE.findall(EXTRA_CUSTOM.read_text(encoding="utf-8-sig")))
    print("%d tooltip lists over 34 directions, %d of them Glorp UI's own"
          % (len(gui_entries),
             sum(1 for e in gui_entries if e[1].startswith("glorpui_svh_visible_"))))
    print("%d hint lines gated by a country trigger" % gated)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
