#!/usr/bin/env python3
"""Turn the EU5 game data into the script this mod evaluates at runtime.

Emits, from `<EU5>/game/in_game/common`:

  scripted_triggers/wtp_generated_rgo_triggers.txt   is this raw material in the province
  scripted_triggers/wtp_generated_availability.txt   could this recipe gain anything here
  script_values/wtp_generated_method_values.txt      what a method scores in a location
  script_values/wtp_generated_goods_values.txt       the best recipe per good, by output

The bonus formula is in eu5data.py, verified against the game's own tooltips.
A method's score is linear in its inputs, so it lands in script as a sum of
`if` clauses over the province's raw materials, divided by the method's total
input weight:

    wtp_bonus_weapon_smith_maintenance = {
        value = 0
        if = { limit = { wtp_province_has_lumber = yes } add = 0.2521 }
        if = { limit = { wtp_province_has_coal = yes }   add = 0.3034 }
        divide = 1.0605
        multiply = 10
    }

Alongside each of those goes its ceiling — the score it would reach with every
raw input present — because that is what says whether a figure is poor or is
everything the recipe can give.

Usage:
    python3 where_to_produce/tools/generate.py <EU5>/game/in_game/common [<CMF>/in_game/common/scripted_effects]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from eu5data import CATEGORY_GROUPS, RGO_MAX_BONUS, Game, Method, load_game  # noqa: E402

MOD_ROOT = Path(__file__).resolve().parent.parent
TRIGGERS_OUT = MOD_ROOT / "in_game" / "common" / "scripted_triggers" / "wtp_generated_rgo_triggers.txt"
VALUES_OUT = MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_method_values.txt"
GOODS_OUT = MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_goods_values.txt"
DISPATCH_OUT = MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_dispatch.txt"
CATALOGUE_OUT = MOD_ROOT / "in_game" / "common" / "scripted_effects" / "wtp_generated_catalogue.txt"
AVAIL_OUT = MOD_ROOT / "in_game" / "common" / "scripted_triggers" / "wtp_generated_availability.txt"
MENU_OUT = MOD_ROOT / "in_game" / "common" / "scripted_effects" / "wtp_generated_menu.txt"
LOC_LANGUAGES = ("english", "russian")
SELECTED_OUT = MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_selected.txt"

BOM = "﻿"
HEADER = "# GENERATED by where_to_produce/tools/generate.py -- do not edit by hand."


def method_id(method: Method, shared: set[str]) -> str:
    """A script-safe name, qualified by building only where a key is reused."""
    if method.key in shared:
        return "%s__%s" % (method.building, method.key)
    return method.key


def resolve_ids(game: Game) -> dict[tuple[str, str], str]:
    """Map every (building, method) to a unique identifier.

    Shared methods are listed by several building types with identical bodies,
    so one script value serves them all. A key that carries *different* bodies
    across buildings has to be split, or the two would silently collide.
    """
    bodies: dict[str, set[tuple]] = {}
    for m in game.methods:
        bodies.setdefault(m.key, set()).add((m.output, tuple(sorted(m.inputs.items()))))
    ambiguous = {key for key, seen in bodies.items() if len(seen) > 1}
    return {(m.building, m.key): method_id(m, ambiguous) for m in game.methods}


def render_triggers(goods: list[str]) -> str:
    out = [BOM + HEADER, "#",
           "# True when some location in this province works that raw material.",
           "# The bonus is province wide, which is what the game's own tooltip reports,",
           "# and the shortlist ranks provinces, so everything here is province scoped.",
           "# Scope: province", ""]
    for good in goods:
        out.append("wtp_province_has_%s = {" % good)
        out.append("\tany_location_in_province = {")
        out.append("\t\traw_material = goods:%s" % good)
        out.append("\t}")
        out.append("}")
        out.append("")
    return "\n".join(out)


def render_values(game: Game, ids: dict[tuple[str, str], str]) -> str:
    out = [BOM + HEADER, "#",
           "# Per production method: the raw material bonus it would get in this",
           "# location, its ceiling, and what it outputs. Every input counts towards",
           "# the divisor, produced goods included -- that is why a ceiling can sit",
           "# well below %g%%." % RGO_MAX_BONUS,
           "# Scope: province", ""]

    emitted: set[str] = set()
    for method in sorted(game.methods, key=lambda m: (m.produced, -m.output, m.building, m.key)):
        raw_inputs = method.raw_inputs(game.raw_goods)
        if not raw_inputs or not method.total_input:
            continue
        name = ids[(method.building, method.key)]
        if name in emitted:
            continue
        emitted.add(name)

        out.append("# %s in %s -- produces %s, output %g, ceiling %.2f%%" % (
            method.key, method.building, method.produced, method.output,
            method.ceiling(game.raw_goods)))
        out.append("wtp_bonus_%s = {" % name)
        out.append("\tvalue = 0")
        for good, amount in sorted(raw_inputs.items()):
            out.append("\tif = { limit = { wtp_province_has_%s = yes } add = %s }" % (
                good, format(amount, "g")))
        out.append("\tdivide = %s" % format(method.total_input, "g"))
        out.append("\tmultiply = %g" % RGO_MAX_BONUS)
        out.append("}")
        out.append("wtp_ceiling_%s = %.4f" % (name, method.ceiling(game.raw_goods)))
        out.append("wtp_output_%s = %s" % (name, format(method.output, "g")))
        out.append("")
    return "\n".join(out)


def render_goods(game: Game, ids: dict[tuple[str, str], str]) -> tuple[str, str]:
    """Per good: what the best recipe available in this province would give.

    Methods are laid out by descending output, so the first one with any of its
    raw materials in the province is the highest yielding one on offer — that is
    the ranking the shortlist wants, with the bonus reported for the same
    recipe rather than for whichever happens to score best.
    """
    avail = [BOM + HEADER, "#",
             "# True when any raw material of that recipe is worked in the province.",
             "# Scope: province", ""]
    values = [BOM + HEADER, "#",
              "# Per good: what the best recipe on offer in this province would give.",
              "# Zero when nothing producing it would gain anything here, which is what",
              "# keeps such provinces off the shortlist.",
              "# Scope: province", ""]

    for good in game.goods_produced:
        chain = []
        seen: set[str] = set()
        for method in game.producing(good):
            name = ids[(method.building, method.key)]
            if name in seen:
                continue
            seen.add(name)
            chain.append((name, method))
        if not chain:
            continue

        for name, method in chain:
            if "wtp_method_available_%s = {" % name in avail:
                continue
            avail.append("# %s in %s" % (method.key, method.building))
            avail.append("wtp_method_available_%s = {" % name)
            avail.append("\tOR = {")
            for material in sorted(method.raw_inputs(game.raw_goods)):
                avail.append("\t\twtp_province_has_%s = yes" % material)
            avail.append("\t}")
            avail.append("}")
            avail.append("")

        values.append("# ---- %s: recipes by descending output ----" % good)
        for label, value_of in (
            ("output", lambda n, m: format(m.output, "g")),
            ("bonus", lambda n, m: "wtp_bonus_%s" % n),
            ("ceiling", lambda n, m: "wtp_ceiling_%s" % n),
        ):
            values.append("wtp_best_%s_%s = {" % (label, good))
            values.append("\tvalue = 0")
            for index, (name, method) in enumerate(chain):
                keyword = "if" if index == 0 else "else_if"
                values.append("\t%s = { limit = { wtp_method_available_%s = yes } value = %s }" % (
                    keyword, name, value_of(name, method)))
            values.append("}")
        values.append("")
    return "\n".join(avail), "\n".join(values)


def render_dispatch(game: Game) -> str:
    """Resolve the three per-good chains against whichever good is selected.

    `order_by` takes one script value, so the good the player picked has to be
    reachable from a single name. It is parked in the `wtp_good` global as a
    goods scope, and these fan out to the matching chain.
    """
    out = [BOM + HEADER, "#",
           "# Scope: province. Zero while no good is selected, which also leaves",
           "# every province out of the shortlist.", ""]
    for label in ("output", "bonus", "ceiling"):
        out.append("wtp_current_%s = {" % label)
        out.append("\tvalue = 0")
        for index, good in enumerate(game.goods_produced):
            keyword = "if" if index == 0 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_good = goods:%s } value = wtp_best_%s_%s }" % (
                keyword, good, label, good))
        out.append("}")
        out.append("")
    return "\n".join(out)


def render_catalogue(game: Game) -> str:
    """The goods the picker offers, as a global list the window can iterate.

    Only goods something could actually produce with a local bonus; the rest
    would be dead entries in the grid.
    """
    out = [BOM + HEADER, "#",
           "# Fill the goods picker, one list per group. The groups follow the",
           "# category of the building that makes the good, which is what the",
           "# player already sorts the world by.",
           "# Scope: any", "",
           "wtp_build_goods_catalogue = {"]
    groups = game.goods_by_group()
    for name, _ in CATEGORY_GROUPS:
        out.append("\tclear_global_variable_list = wtp_goods_%s" % name)
    for name, _ in CATEGORY_GROUPS:
        out.append("")
        out.append("\t# %s: %d" % (name, len(groups[name])))
        for good in groups[name]:
            out.append("\tadd_to_global_variable_list = { name = wtp_goods_%s target = goods:%s }" % (
                name, good))
    out.append("}")
    out.append("")
    return "\n".join(out)


def check_cmm_arguments(cmf_effects: Path) -> None:
    """Warn when a cmm_ call uses an argument name CMF does not declare."""
    declared = "".join(p.read_text(encoding="utf-8-sig") for p in cmf_effects.glob("*.txt"))
    ours = "".join(p.read_text(encoding="utf-8-sig")
                   for p in (MOD_ROOT / "in_game" / "common" / "scripted_effects").glob("*.txt"))
    for call in re.finditer(r"(cmm_[a-z_]+) = \{([^{}]*)\}", ours):
        name, body = call.group(1), call.group(2)
        decl = re.search(r"^%s = \{(.*?)^\}" % re.escape(name), declared, re.S | re.M)
        if decl is None:
            print("unknown CMM effect: %s" % name, file=sys.stderr)
            continue
        allowed = set(re.findall(r"\$(\w+)\$", decl.group(1)))
        extra = set(re.findall(r"^\s*(\w+)\s*=", body, re.M)) - allowed
        if extra:
            print("%s called with %s; CMF declares %s"
                  % (name, sorted(extra), sorted(allowed)), file=sys.stderr)


def render_menu(game: Game, ids) -> tuple[str, str]:
    """The Mod Menu side: goods pickers, the recipe list, and the dispatch.

    Once a recipe is chosen its output is the same everywhere, so provinces are
    ranked on the bonus alone and `wtp_selected_bonus` is all the ordering needs.
    """
    groups = game.goods_by_group()
    out = [BOM + HEADER, "#", "# Scope: country", ""]
    loc = ["l_english:"]

    # Turning a dropdown ordinal back into the good it stands for.
    # Option 1 of every picker is "nothing chosen", so opening the menu does not
    # look like four goods are already selected and one picker can be used on its
    # own. Goods therefore start at ordinal 2.
    for group, _ in CATEGORY_GROUPS:
        out.append("wtp_apply_pick_%s = {" % group)
        for index, good in enumerate(groups[group], start=2):
            keyword = "if" if index == 2 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_pick_%s = %d }" % (keyword, group, index))
            out.append("\t\tset_global_variable = { name = wtp_good value = goods:%s }" % good)
            out.append("\t}")
        out.append("}")
        out.append("")
        loc.append(' wtp__pick_%s_option_1_name: "$WTP_PICK_NONE$"' % group)
        for index, good in enumerate(groups[group], start=2):
            loc.append(' wtp__pick_%s_option_%d_name: "$%s$"' % (group, index, good))

    # Rebuilding the recipe list for whichever good is selected.
    out.append("# Fill the recipe list. Scope: country")
    out.append("wtp_fill_recipes = {")
    for gi, good in enumerate(game.goods_produced):
        keyword = "if" if gi == 0 else "else_if"
        out.append("\t%s = { limit = { global_var:wtp_good = goods:%s }" % (keyword, good))
        seen = set()
        rows = []
        for method in game.producing(good):
            name = ids[(method.building, method.key)]
            if name in seen:
                continue
            seen.add(name)
            rows.append((name, method))
        for name, method in rows:
            out.append("\t\tcmm_add_global_settings_list_item = {")
            out.append("\t\t\tmod_id = wtp")
            out.append("\t\t\tsetting_id = recipes")
            out.append("\t\t\tvalue = flag:%s" % name)
            out.append("\t\t\tname = wtp_recipe_%s" % name)
            out.append("\t\t}")
        out.append("\t}")
        for name, method in rows:
            loc.append(' wtp_recipe_%s: "$%s$ — $%s$"' % (name, method.building, method.produced))
    out.append("}")
    out.append("")

    return "\n".join(out), "\n".join(loc) + "\n"


def render_selected(game: Game, ids) -> str:
    """Bonus and ceiling of the ticked recipe, keyed on the wtp_recipe global."""
    out = [BOM + HEADER, "#", "# Scope: province", ""]
    names = []
    seen = set()
    for method in game.methods:
        if not method.raw_inputs(game.raw_goods):
            continue
        name = ids[(method.building, method.key)]
        if name in seen:
            continue
        seen.add(name)
        names.append(name)
    # Keyed on the ticked recipe, for the ranking.
    for label in ("bonus",):
        out.append("wtp_selected_%s = {" % label)
        out.append("\tvalue = 0")
        for index, name in enumerate(sorted(names)):
            keyword = "if" if index == 0 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_recipe = flag:%s } value = wtp_%s_%s }" % (
                keyword, name, label, name))
        out.append("}")
        out.append("")

    # Keyed on the row being labelled, for the ceiling column, which has to read
    # every recipe rather than only the ticked one.
    out.append("wtp_selected_ceiling = {")
    out.append("\tvalue = 0")
    for index, name in enumerate(sorted(names)):
        keyword = "if" if index == 0 else "else_if"
        out.append("\t%s = { limit = { scope:wtp_row_recipe = flag:%s } value = wtp_ceiling_%s }" % (
            keyword, name, name))
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) not in (2, 3):
        print(__doc__)
        return 2
    common = Path(sys.argv[1])
    missing = [n for n in ("goods", "production_methods", "building_types")
               if not (common / n).is_dir()]
    if missing:
        print("missing under %s: %s" % (common, ", ".join(missing)), file=sys.stderr)
        return 1

    game = load_game(common)
    ids = resolve_ids(game)

    used_goods = sorted({
        good
        for m in game.methods
        for good in m.raw_inputs(game.raw_goods)
    })

    avail, values = render_goods(game, ids)
    menu, menu_loc = render_menu(game, ids)

    for path, text in ((TRIGGERS_OUT, render_triggers(used_goods)),
                       (VALUES_OUT, render_values(game, ids)),
                       (AVAIL_OUT, avail),
                       (GOODS_OUT, values),
                       (DISPATCH_OUT, render_dispatch(game)),
                       (CATALOGUE_OUT, render_catalogue(game)),
                       (MENU_OUT, menu),
                       (SELECTED_OUT, render_selected(game, ids)),
                       ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    scored = {ids[(m.building, m.key)] for m in game.methods if m.raw_inputs(game.raw_goods)}
    # A macro called with an argument CMF does not declare fails silently at
    # load and takes the rest of its effect with it -- which is how one `step`
    # instead of `step_value` emptied both lists.
    if len(sys.argv) > 2:
        check_cmm_arguments(Path(sys.argv[2]))

    counts = {name: len(rows) + 1 for name, rows in game.goods_by_group().items()}
    registration = (MOD_ROOT / "in_game" / "common" / "scripted_effects"
                    / "wtp_registration.txt").read_text(encoding="utf-8-sig")
    for name, want in counts.items():
        found = re.search(r"setting_id = pick_%s(?:.|\n)*?option_count = (\d+)" % name,
                          registration)
        if found and int(found.group(1)) != want:
            print("option_count for pick_%s is %s, should be %d"
                  % (name, found.group(1), want), file=sys.stderr)

    print("goods per picker:         %s" % counts)
    print("raw materials referenced: %d" % len(used_goods))
    print("methods scored:           %d" % len(scored))
    print("goods reachable:          %d" % len(game.goods_produced))
    for language in LOC_LANGUAGES:
        path = MOD_ROOT / "main_menu" / "localization" / language / ("wtp_generated_l_%s.yml" % language)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\ufeff" + menu_loc.replace("l_english:", "l_%s:" % language, 1),
                        encoding="utf-8")

    for path in (TRIGGERS_OUT, VALUES_OUT, AVAIL_OUT, GOODS_OUT, DISPATCH_OUT,
                 CATALOGUE_OUT, MENU_OUT, SELECTED_OUT):
        print("wrote %s" % path.relative_to(MOD_ROOT.parent))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
