#!/usr/bin/env python3
"""Turn the EU5 game data into the script this mod evaluates at runtime.

Emits, from `<EU5>/game/in_game/common`:

  scripted_triggers/wtp_generated_rgo_triggers.txt   is this raw material in the province
  scripted_triggers/wtp_generated_availability.txt   is this recipe worth offering at all
  script_values/wtp_generated_method_values.txt      what one method scores in a province
  script_values/wtp_generated_scoring.txt            the same, reached through a recipe flag
  scripted_effects/wtp_generated_menu.txt            the pickers, the candidates, the index
  localization/*/wtp_generated_l_*.yml               picker options, method names, recipes

The bonus formula is in eu5data.py, verified against the game's own tooltips.
A method's score is linear in its inputs, so it lands in script as a sum of
`if` clauses over the province's raw materials, divided by the method's total
input weight:

    wtp_bonus_weapon_smith_maintenance = {
        value = 0
        if = { limit = { wtp_province_has_lumber = yes } add = 0.2521 }
        if = { limit = { wtp_province_has_coal = yes }   add = 0.3034 }
        divide = 1.0605
        multiply = 10
    }

Alongside each of those go its ceiling — the score it would reach with every raw
input present — and the volume it would actually turn out at that score, since
efficiency multiplies output and a big method at a poor percentage still beats a
small one at its best.

Usage:
    python3 where_to_produce/tools/generate.py <EU5>/game/in_game/common [<CMF>/in_game/common/scripted_effects]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from eu5data import CATEGORY_GROUPS, RGO_MAX_BONUS, Game, Method, load_game, load_dir, find, scalar  # noqa: E402

MOD_ROOT = Path(__file__).resolve().parent.parent
OUT = MOD_ROOT / "in_game" / "common"
TRIGGERS_OUT = OUT / "scripted_triggers" / "wtp_generated_rgo_triggers.txt"
AVAIL_OUT = OUT / "scripted_triggers" / "wtp_generated_availability.txt"
VALUES_OUT = OUT / "script_values" / "wtp_generated_method_values.txt"
SCORING_OUT = OUT / "script_values" / "wtp_generated_scoring.txt"
MENU_OUT = OUT / "scripted_effects" / "wtp_generated_menu.txt"
LOC_LANGUAGES = ("english", "russian")

# Written by designs this one replaced. The generator deletes them rather than
# leave the game parsing them on every load.
RETIRED = (
    OUT / "script_values" / "wtp_generated_goods_values.txt",
    OUT / "script_values" / "wtp_generated_dispatch.txt",
    OUT / "script_values" / "wtp_generated_selected.txt",
    OUT / "scripted_effects" / "wtp_generated_catalogue.txt",
)

BOM = "﻿"
HEADER = "# GENERATED by where_to_produce/tools/generate.py -- do not edit by hand."

# Both lists are registered at whatever height they currently need, so these are
# only the ceilings the hand written row writers reach up to.
RECIPE_ROWS = 20
PROVINCE_ROWS = 10


def amount(value: float) -> str:
    """An input amount the way the building panel shows it."""
    return ("%.2f" % value).rstrip("0").rstrip(".") or "0"


def method_id(method: Method, shared: set[str]) -> str:
    """A script-safe name, qualified by building only where a key is reused."""
    if method.key in shared:
        return "%s__%s" % (method.building, method.key)
    return method.key


def resolve_ids(game: Game) -> dict[tuple[str, str], str]:
    """Map every (building, method) to a unique identifier.

    Shared methods are listed by several building types with identical bodies,
    so one script value serves them all. A key that carries *different* bodies
    across buildings has to be split, or the two would silently collide.
    """
    bodies: dict[str, set[tuple]] = {}
    for m in game.methods:
        bodies.setdefault(m.key, set()).add((m.output, tuple(sorted(m.inputs.items()))))
    ambiguous = {key for key, seen in bodies.items() if len(seen) > 1}
    return {(m.building, m.key): method_id(m, ambiguous) for m in game.methods}


def recipes_of(game: Game, good: str, ids) -> list[tuple[str, Method]]:
    """The recipes making one good, best output first, without duplicates."""
    rows = []
    seen: set[str] = set()
    for method in game.producing(good):
        name = ids[(method.building, method.key)]
        if name in seen:
            continue
        seen.add(name)
        rows.append((name, method))
    return rows


def brace_match(text: str, open_at: int) -> str:
    """The `{ ... }` starting at `open_at`, braces included."""
    depth = 0
    for i in range(open_at, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_at:i + 1]
    return "{}"


def country_gates(building_dir: Path) -> dict[str, str]:
    """Each building's `country_potential`, verbatim, keyed by building.

    Taken as raw text rather than round tripped through the parser: it is an
    ordinary country scoped trigger and the game's own wording is the only
    version guaranteed to mean what the game means. `has_reform`,
    `has_or_had_tag`, `culture`, `custom_tooltip` and `always = no` all appear in
    these, and all of them work unchanged inside a scripted trigger.
    """
    gates: dict[str, str] = {}
    for path in sorted(building_dir.glob("*.txt")):
        if "readme" in path.name.lower():
            continue
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        for top in re.finditer(r"^(\w+) = \{", text, re.M):
            body = brace_match(text, top.end() - 1)
            gate = re.search(r"^\tcountry_potential = \{", body, re.M)
            if gate:
                inner = brace_match(body, gate.end() - 1)[1:-1]
                lines = [ln.strip() for ln in inner.splitlines() if ln.strip()]
                if lines:
                    gates[top.group(1)] = "\n".join("\t" + ln for ln in lines)
    return gates


def render_triggers(goods: list[str]) -> str:
    out = [BOM + HEADER, "#",
           "# True when some location in this province works that raw material.",
           "# The bonus is province wide, which is what the game's own tooltip reports,",
           "# and the shortlist ranks provinces, so everything here is province scoped.",
           "# Scope: province", ""]
    for good in goods:
        out.append("wtp_province_has_%s = {" % good)
        out.append("\tany_location_in_province = {")
        out.append("\t\traw_material = goods:%s" % good)
        out.append("\t}")
        out.append("}")
        out.append("")
    return "\n".join(out)


def render_availability(game: Game, ids, gates: dict[str, str]) -> str:
    """Whether a recipe is worth putting in front of this country at all.

    Three things make one worthless, and all three are in the game files:

      * the building carries a `country_potential` this country fails — a
        Japanese clan reform, an English tag, or a flat `always = no`;
      * the building is special or foreign, so it is not something the player
        builds in the ordinary way;
      * nowhere in the realm works any of the raw materials the recipe could
        take a bonus from, which is the only thing this mod has to say about it.
    """
    out = [BOM + HEADER, "#",
           "# Whether a recipe is worth offering. Reads the realm's raw materials",
           "# from the globals wtp_scan_realm_materials leaves behind, and carries the",
           "# building's own country_potential verbatim where it has one.",
           "# Scope: country", ""]

    buildings = load_dir(Path(game_common) / "building_types")
    emitted: set[str] = set()
    for method in sorted(game.methods, key=lambda m: (m.produced, -m.output, m.building, m.key)):
        raw_inputs = method.raw_inputs(game.raw_goods)
        if not raw_inputs or not method.total_input:
            continue
        name = ids[(method.building, method.key)]
        if name in emitted:
            continue
        emitted.add(name)

        entries = buildings[method.building]
        special = scalar(entries, "is_special") == "yes" or scalar(entries, "is_foreign") == "yes"
        gate = gates.get(method.building)

        out.append("# %s in %s" % (method.key, method.building))
        out.append("wtp_available_%s = {" % name)
        if special:
            out.append("\t# %s is special or foreign: not built the ordinary way." % method.building)
            out.append("\talways = no")
        else:
            out.append("\tOR = {")
            for good in sorted(raw_inputs):
                out.append("\t\thas_global_variable = wtp_realm_has_%s" % good)
            out.append("\t}")
            if gate is not None:
                out.append("\t# country_potential of %s, verbatim" % method.building)
                out.append(gate)
        out.append("}")
        out.append("")
    return "\n".join(out)


def render_values(game: Game, ids) -> str:
    out = [BOM + HEADER, "#",
           "# Per production method, in one province: the raw material bonus it would",
           "# get, the volume it would turn out at that bonus, its ceiling, and the",
           "# volume at that ceiling. Every input counts towards the divisor, produced",
           "# goods included -- that is why a ceiling can sit well below %g%%." % RGO_MAX_BONUS,
           "#",
           "# Efficiency multiplies output, so volume is what makes two different",
           "# recipes comparable: a method at half its ceiling can still turn out more",
           "# than a small one running at the full bonus.",
           "#",
           "# The two constants are rounded here rather than in the menu, because a",
           "# data field prints whatever it is given and 3.7533% reads as noise.",
           "# Scope: province", ""]

    emitted: set[str] = set()
    for method in sorted(game.methods, key=lambda m: (m.produced, -m.output, m.building, m.key)):
        raw_inputs = method.raw_inputs(game.raw_goods)
        if not raw_inputs or not method.total_input:
            continue
        name = ids[(method.building, method.key)]
        if name in emitted:
            continue
        emitted.add(name)

        ceiling = method.ceiling(game.raw_goods)
        out.append("# %s in %s -- produces %s, output %g, ceiling %.2f%%" % (
            method.key, method.building, method.produced, method.output, ceiling))
        out.append("wtp_bonus_%s = {" % name)
        out.append("\tvalue = 0")
        for good, value in sorted(raw_inputs.items()):
            out.append("\tif = { limit = { wtp_province_has_%s = yes } add = %s }" % (
                good, format(value, "g")))
        out.append("\tdivide = %s" % format(method.total_input, "g"))
        out.append("\tmultiply = %g" % RGO_MAX_BONUS)
        out.append("}")
        out.append("wtp_volume_%s = {" % name)
        out.append("\tvalue = wtp_bonus_%s" % name)
        out.append("\tdivide = 100")
        out.append("\tadd = 1")
        out.append("\tmultiply = %s" % format(method.output, "g"))
        out.append("}")
        out.append("wtp_ceiling_%s = %s" % (name, round(ceiling, 2)))
        out.append("wtp_peak_%s = %s" % (name, round(method.output * (1 + ceiling / 100), 2)))
        out.append("")
    return "\n".join(out)


def render_scoring(game: Game, ids) -> str:
    """What one recipe is worth, reached through the flag that stands for it.

    Two hops — the good first, then the recipe within it — rather than one chain
    over every method in the game. The shortlist evaluates this once per province
    per ticked recipe, so the difference between forty-odd comparisons and two
    hundred is worth having.
    """
    out = [BOM + HEADER, "#",
           "# Scoring a province: `scope:wtp_scored_recipe` names the recipe and the",
           "# current scope is the province. Writing a recipe row:",
           "# `scope:wtp_pending_recipe` names it and the numbers are constants.",
           "# Scope: province for the first pair, any for the second", ""]

    for label in ("bonus", "volume"):
        out.append("wtp_scored_%s = {" % label)
        out.append("\tvalue = 0")
        for index, good in enumerate(game.goods_produced):
            keyword = "if" if index == 0 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_good = goods:%s }"
                       " value = wtp_scored_%s_%s }" % (keyword, good, label, good))
        out.append("}")
        out.append("")

    for label, source in (("ceiling", "wtp_ceiling"), ("peak", "wtp_peak")):
        out.append("wtp_pending_%s = {" % label)
        out.append("\tvalue = 0")
        for index, good in enumerate(game.goods_produced):
            keyword = "if" if index == 0 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_good = goods:%s }"
                       " value = wtp_pending_%s_%s }" % (keyword, good, label, good))
        out.append("}")
        out.append("")

    for good in game.goods_produced:
        rows = recipes_of(game, good, ids)
        for label, source, scope in (("bonus", "wtp_bonus", "wtp_scored_recipe"),
                                     ("volume", "wtp_volume", "wtp_scored_recipe")):
            out.append("wtp_scored_%s_%s = {" % (label, good))
            out.append("\tvalue = 0")
            for index, (name, _) in enumerate(rows):
                keyword = "if" if index == 0 else "else_if"
                out.append("\t%s = { limit = { scope:%s = flag:wtp_recipe_%s }"
                           " value = %s_%s }" % (keyword, scope, name, source, name))
            out.append("}")
        for label, source in (("ceiling", "wtp_ceiling"), ("peak", "wtp_peak")):
            out.append("wtp_pending_%s_%s = {" % (label, good))
            out.append("\tvalue = 0")
            for index, (name, _) in enumerate(rows):
                keyword = "if" if index == 0 else "else_if"
                out.append("\t%s = { limit = { scope:wtp_pending_recipe = flag:wtp_recipe_%s }"
                           " value = %s_%s }" % (keyword, name, source, name))
            out.append("}")
        out.append("")
    return "\n".join(out)


def render_menu(game: Game, ids, used_goods: list[str]) -> tuple[str, str]:
    """The pickers, the candidate recipes per good, and two lookups.

    A recipe travels as the flag naming its own localization key. That labels the
    row and identifies it everywhere else; the tooltip key cannot be derived from
    it in script, so a variable map carries recipe flag -> tooltip flag.
    """
    groups = game.goods_by_group()
    out = [BOM + HEADER, "#", "# Scope: country", ""]
    loc = ["l_english:"]

    # Turning a dropdown ordinal back into the good it stands for.
    # Option 1 of every picker is "nothing chosen", so opening the menu does not
    # look like four goods are already selected and one picker can be used on its
    # own. Goods therefore start at ordinal 2.
    for group, _ in CATEGORY_GROUPS:
        out.append("wtp_apply_pick_%s = {" % group)
        for index, good in enumerate(groups[group], start=2):
            keyword = "if" if index == 2 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_pick_%s = %d }" % (keyword, group, index))
            out.append("\t\tset_global_variable = { name = wtp_good value = goods:%s }" % good)
            out.append("\t}")
        out.append("}")
        out.append("")
        loc.append(' wtp__pick_%s_option_1_name: "$WTP_PICK_NONE$"' % group)
        for index, good in enumerate(groups[group], start=2):
            loc.append(' wtp__pick_%s_option_%d_name: "$%s$"' % (group, index, good))

    # Which raw materials the realm works at all. One pass over owned locations
    # answers it for every recipe at once.
    out.append("# Scope: any")
    out.append("wtp_forget_realm_materials = {")
    for good in used_goods:
        out.append("\tif = { limit = { has_global_variable = wtp_realm_has_%s }"
                   " remove_global_variable = wtp_realm_has_%s }" % (good, good))
    out.append("}")
    out.append("")
    out.append("# Scope: location")
    out.append("wtp_note_realm_material = {")
    for index, good in enumerate(used_goods):
        keyword = "if" if index == 0 else "else_if"
        out.append("\t%s = { limit = { raw_material = goods:%s }" % (keyword, good))
        out.append("\t\tset_global_variable = { name = wtp_realm_has_%s value = yes }" % good)
        out.append("\t}")
    out.append("}")
    out.append("")

    # Recipe flag -> tooltip flag. Script cannot build the second name out of the
    # first, and the row's tooltip key is whatever this hands back.
    out.append("# Scope: any")
    out.append("wtp_build_recipe_index = {")
    out.append("\tclear_global_variable_map = wtp_recipe_tooltip")
    for name in sorted({ids[(m.building, m.key)] for m in game.methods
                        if m.raw_inputs(game.raw_goods)}):
        out.append("\tadd_to_global_variable_map = { name = wtp_recipe_tooltip"
                   " key = flag:wtp_recipe_%s value = flag:wtp_recipe_%s_desc }" % (name, name))
    out.append("}")
    out.append("")

    out.append("# Every recipe that makes the chosen good, best output first, minus the")
    out.append("# ones wtp_offer turns away. Scope: country")
    out.append("wtp_collect_recipes = {")
    out.append("\tclear_global_variable_list = wtp_shown_recipes")
    out.append("\tset_variable = { name = wtp_recipe_count value = 0 }")
    out.append("")
    for gi, good in enumerate(game.goods_produced):
        keyword = "if" if gi == 0 else "else_if"
        out.append("\t%s = { limit = { global_var:wtp_good = goods:%s }" % (keyword, good))
        rows = recipes_of(game, good, ids)[:RECIPE_ROWS]
        for name, _ in rows:
            out.append("\t\twtp_offer = { m = %s }" % name)
        out.append("\t}")
        for name, method in rows:
            loc += recipe_localization(game, name, method)
    out.append("}")
    out.append("")

    return "\n".join(out), "\n".join(loc) + "\n"


def recipe_localization(game: Game, name: str, method: Method) -> list[str]:
    """The row label and its tooltip.

    The label is the game's own name for the method and nothing else: the row is
    a single line of text that the engine shrinks to fit, so a recipe written
    into it left every row at a different font size. The recipe goes in the
    tooltip, where it has room.

    Nothing here is a word in any language — the method, the goods and the three
    captions are all `$key$` references — so one generated file serves every
    localization the mod ships.
    """
    inputs = " + ".join("%s $%s$" % (amount(value), good)
                        for good, value in sorted(method.inputs.items(),
                                                  key=lambda kv: (-kv[1], kv[0])))
    produced = "%s $%s$" % (amount(method.output), method.produced)
    local = ", ".join("$%s$" % good for good in sorted(method.raw_inputs(game.raw_goods)))

    desc = "$WTP_IN$ %s\\n$WTP_OUT$ %s\\n$WTP_FROM_RGO$ %s" % (inputs or "—", produced, local)

    return [' wtp_recipe_%s: "$%s$"' % (name, method.key),
            ' wtp_recipe_%s_desc: "%s"' % (name, desc)]


def check_cmm_arguments(cmf_effects: Path) -> None:
    """Warn when a cmm_ call uses an argument name CMF does not declare."""
    declared = "".join(p.read_text(encoding="utf-8-sig") for p in cmf_effects.glob("*.txt"))
    ours = "".join(p.read_text(encoding="utf-8-sig")
                   for folder in ("scripted_effects", "scripted_guis")
                   for p in (OUT / folder).glob("*.txt"))
    for call in re.finditer(r"(cmm_[a-z_]+) = \{([^{}]*)\}", ours):
        name, body = call.group(1), call.group(2)
        decl = re.search(r"^%s = \{(.*?)^\}" % re.escape(name), declared, re.S | re.M)
        if decl is None:
            print("unknown CMM effect: %s" % name, file=sys.stderr)
            continue
        allowed = set(re.findall(r"\$(\w+)\$", decl.group(1)))
        extra = set(re.findall(r"\b(\w+)\s*=", body)) - allowed
        if extra:
            print("%s called with %s; CMF declares %s"
                  % (name, sorted(extra), sorted(allowed)), file=sys.stderr)


def check_hand_written(game: Game, ids) -> None:
    """Warn when the hand written side has drifted from the game data."""
    registration = (OUT / "scripted_effects" / "wtp_registration.txt").read_text(encoding="utf-8-sig")
    effects = (OUT / "scripted_effects" / "wtp_effects.txt").read_text(encoding="utf-8-sig")

    for name, rows in game.goods_by_group().items():
        want = len(rows) + 1
        found = re.search(r"setting_id = pick_%s(?:.|\n)*?option_count = (\d+)" % name,
                          registration)
        if found and int(found.group(1)) != want:
            print("option_count for pick_%s is %s, should be %d"
                  % (name, found.group(1), want), file=sys.stderr)

    widest = max((len(recipes_of(game, good, ids)), good) for good in game.goods_produced)
    if widest[0] > RECIPE_ROWS:
        print("%s has %d recipes and the row writers stop at %d; raise RECIPE_ROWS "
              "and both switches in wtp_effects.txt"
              % (widest[1], widest[0], RECIPE_ROWS), file=sys.stderr)

    for n in range(1, RECIPE_ROWS + 1):
        for shape in ("%d = { wtp_write_recipe_row = { n = %d } }" % (n, n),
                      "%d = { wtp_size_recipe_list = { n = %d } }" % (n, n)):
            if shape not in effects:
                print("wtp_effects.txt is missing `%s`" % shape, file=sys.stderr)
    for n in range(1, PROVINCE_ROWS + 1):
        for shape in ("%d = { wtp_write_province_row = { n = %d } }" % (n, n),
                      "%d = { wtp_size_province_list = { n = %d } }" % (n, n)):
            if shape not in effects:
                print("wtp_effects.txt is missing `%s`" % shape, file=sys.stderr)


def main() -> int:
    global game_common
    if len(sys.argv) not in (2, 3):
        print(__doc__)
        return 2
    common = Path(sys.argv[1])
    game_common = str(common)
    missing = [n for n in ("goods", "production_methods", "building_types")
               if not (common / n).is_dir()]
    if missing:
        print("missing under %s: %s" % (common, ", ".join(missing)), file=sys.stderr)
        return 1

    game = load_game(common)
    ids = resolve_ids(game)
    gates = country_gates(common / "building_types")

    used_goods = sorted({
        good
        for m in game.methods
        for good in m.raw_inputs(game.raw_goods)
    })

    menu, menu_loc = render_menu(game, ids, used_goods)

    for path, text in ((TRIGGERS_OUT, render_triggers(used_goods)),
                       (AVAIL_OUT, render_availability(game, ids, gates)),
                       (VALUES_OUT, render_values(game, ids)),
                       (SCORING_OUT, render_scoring(game, ids)),
                       (MENU_OUT, menu),
                       ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    for path in RETIRED:
        if path.exists():
            path.unlink()
            print("removed %s" % path.relative_to(MOD_ROOT.parent))

    if len(sys.argv) > 2:
        # A macro called with an argument CMF does not declare fails silently at
        # load and takes the rest of its effect with it -- which is how one `step`
        # instead of `step_value` emptied both lists.
        check_cmm_arguments(Path(sys.argv[2]))
    check_hand_written(game, ids)

    scored = {ids[(m.building, m.key)] for m in game.methods if m.raw_inputs(game.raw_goods)}
    gated = sum(1 for m in game.methods
                if m.raw_inputs(game.raw_goods) and m.building in gates)
    print("goods per picker:         %s" % {n: len(r) + 1
                                            for n, r in game.goods_by_group().items()})
    print("raw materials referenced: %d" % len(used_goods))
    print("methods scored:           %d" % len(scored))
    print("goods reachable:          %d" % len(game.goods_produced))
    print("widest good:              %d recipes" % max(
        len(recipes_of(game, good, ids)) for good in game.goods_produced))
    print("methods behind a country_potential: %d" % gated)

    for language in LOC_LANGUAGES:
        path = MOD_ROOT / "main_menu" / "localization" / language / ("wtp_generated_l_%s.yml" % language)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("﻿" + menu_loc.replace("l_english:", "l_%s:" % language, 1),
                        encoding="utf-8")

    for path in (TRIGGERS_OUT, AVAIL_OUT, VALUES_OUT, SCORING_OUT, MENU_OUT):
        print("wrote %s" % path.relative_to(MOD_ROOT.parent))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
