#!/usr/bin/env python3
"""Turn the EU5 game data into the script this mod evaluates at runtime.

Emits, from `<EU5>/game/in_game/common`:

  scripted_triggers/wtp_generated_rgo_triggers.txt   is this raw material in the province
  script_values/wtp_generated_method_values.txt      what one method scores in a province
  script_values/wtp_generated_scoring.txt            the same, reached through the ticked recipe
  scripted_effects/wtp_generated_menu.txt            the goods pickers and the recipe rows
  localization/*/wtp_generated_l_*.yml               picker options, recipe names and recipes

The bonus formula is in eu5data.py, verified against the game's own tooltips.
A method's score is linear in its inputs, so it lands in script as a sum of
`if` clauses over the province's raw materials, divided by the method's total
input weight:

    wtp_bonus_weapon_smith_maintenance = {
        value = 0
        if = { limit = { wtp_province_has_lumber = yes } add = 0.2521 }
        if = { limit = { wtp_province_has_coal = yes }   add = 0.3034 }
        divide = 1.0605
        multiply = 10
    }

Alongside each of those go its ceiling — the score it would reach with every raw
input present — and the volume it would actually turn out at that score, since
efficiency multiplies output and a big method at a poor percentage still beats a
small one at its best.

Usage:
    python3 where_to_produce/tools/generate.py <EU5>/game/in_game/common [<CMF>/in_game/common/scripted_effects]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from eu5data import CATEGORY_GROUPS, RGO_MAX_BONUS, Game, Method, load_game  # noqa: E402

MOD_ROOT = Path(__file__).resolve().parent.parent
TRIGGERS_OUT = MOD_ROOT / "in_game" / "common" / "scripted_triggers" / "wtp_generated_rgo_triggers.txt"
VALUES_OUT = MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_method_values.txt"
SCORING_OUT = MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_scoring.txt"
MENU_OUT = MOD_ROOT / "in_game" / "common" / "scripted_effects" / "wtp_generated_menu.txt"
LOC_LANGUAGES = ("english", "russian")

# Written by an earlier design that ranked provinces by "the best recipe on offer
# here". The player picks the recipes now, so nothing reads these; they are
# deleted rather than left for the game to parse on every load.
RETIRED = (
    MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_goods_values.txt",
    MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_dispatch.txt",
    MOD_ROOT / "in_game" / "common" / "script_values" / "wtp_generated_selected.txt",
    MOD_ROOT / "in_game" / "common" / "scripted_triggers" / "wtp_generated_availability.txt",
    MOD_ROOT / "in_game" / "common" / "scripted_effects" / "wtp_generated_catalogue.txt",
)

BOM = "﻿"
HEADER = "# GENERATED by where_to_produce/tools/generate.py -- do not edit by hand."

# The recipe list is registered once at its full height and written in place, so
# it has to be at least as tall as the widest good. Anything past this is dropped,
# and main() says so rather than letting a recipe quietly disappear.
RECIPE_ROWS = 20


def amount(value: float) -> str:
    """An input amount the way the building panel shows it."""
    return ("%.2f" % value).rstrip("0").rstrip(".") or "0"


def method_id(method: Method, shared: set[str]) -> str:
    """A script-safe name, qualified by building only where a key is reused."""
    if method.key in shared:
        return "%s__%s" % (method.building, method.key)
    return method.key


def resolve_ids(game: Game) -> dict[tuple[str, str], str]:
    """Map every (building, method) to a unique identifier.

    Shared methods are listed by several building types with identical bodies,
    so one script value serves them all. A key that carries *different* bodies
    across buildings has to be split, or the two would silently collide.
    """
    bodies: dict[str, set[tuple]] = {}
    for m in game.methods:
        bodies.setdefault(m.key, set()).add((m.output, tuple(sorted(m.inputs.items()))))
    ambiguous = {key for key, seen in bodies.items() if len(seen) > 1}
    return {(m.building, m.key): method_id(m, ambiguous) for m in game.methods}


def recipes_of(game: Game, good: str, ids) -> list[tuple[str, Method]]:
    """The recipes making one good, best output first, without duplicates."""
    rows = []
    seen: set[str] = set()
    for method in game.producing(good):
        name = ids[(method.building, method.key)]
        if name in seen:
            continue
        seen.add(name)
        rows.append((name, method))
    return rows


def render_triggers(goods: list[str]) -> str:
    out = [BOM + HEADER, "#",
           "# True when some location in this province works that raw material.",
           "# The bonus is province wide, which is what the game's own tooltip reports,",
           "# and the shortlist ranks provinces, so everything here is province scoped.",
           "# Scope: province", ""]
    for good in goods:
        out.append("wtp_province_has_%s = {" % good)
        out.append("\tany_location_in_province = {")
        out.append("\t\traw_material = goods:%s" % good)
        out.append("\t}")
        out.append("}")
        out.append("")
    return "\n".join(out)


def render_values(game: Game, ids: dict[tuple[str, str], str]) -> str:
    out = [BOM + HEADER, "#",
           "# Per production method, in one province: the raw material bonus it would",
           "# get, the volume it would turn out at that bonus, its ceiling, and the",
           "# volume at that ceiling. Every input counts towards the divisor, produced",
           "# goods included -- that is why a ceiling can sit well below %g%%." % RGO_MAX_BONUS,
           "#",
           "# Efficiency multiplies output, so volume is what makes two different",
           "# recipes comparable: a method at half its ceiling can still turn out more",
           "# than a small one running at the full bonus.",
           "# Scope: province", ""]

    emitted: set[str] = set()
    for method in sorted(game.methods, key=lambda m: (m.produced, -m.output, m.building, m.key)):
        raw_inputs = method.raw_inputs(game.raw_goods)
        if not raw_inputs or not method.total_input:
            continue
        name = ids[(method.building, method.key)]
        if name in emitted:
            continue
        emitted.add(name)

        ceiling = method.ceiling(game.raw_goods)
        out.append("# %s in %s -- produces %s, output %g, ceiling %.2f%%" % (
            method.key, method.building, method.produced, method.output, ceiling))
        out.append("wtp_bonus_%s = {" % name)
        out.append("\tvalue = 0")
        for good, value in sorted(raw_inputs.items()):
            out.append("\tif = { limit = { wtp_province_has_%s = yes } add = %s }" % (
                good, format(value, "g")))
        out.append("\tdivide = %s" % format(method.total_input, "g"))
        out.append("\tmultiply = %g" % RGO_MAX_BONUS)
        out.append("}")
        out.append("wtp_volume_%s = {" % name)
        out.append("\tvalue = wtp_bonus_%s" % name)
        out.append("\tdivide = 100")
        out.append("\tadd = 1")
        out.append("\tmultiply = %s" % format(method.output, "g"))
        out.append("}")
        out.append("wtp_ceiling_%s = %.4f" % (name, ceiling))
        out.append("wtp_peak_%s = %.4f" % (name, method.output * (1 + ceiling / 100)))
        out.append("")
    return "\n".join(out)


def render_scoring(game: Game, ids) -> str:
    """What the recipe being scored gets in the province being scored.

    Reached in two hops — the good first, then the recipe within it — rather than
    as one chain over every method in the game. The shortlist evaluates this once
    per province per ticked recipe, so the difference between forty-odd
    comparisons and two hundred is worth having.
    """
    out = [BOM + HEADER, "#",
           "# `scope:wtp_scored_recipe` names the recipe, the current scope is the",
           "# province. Both are set by wtp_score_province.",
           "# Scope: province", ""]

    for label in ("bonus", "volume"):
        out.append("wtp_scored_%s = {" % label)
        out.append("\tvalue = 0")
        for index, good in enumerate(game.goods_produced):
            keyword = "if" if index == 0 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_good = goods:%s }"
                       " value = wtp_scored_%s_%s }" % (keyword, good, label, good))
        out.append("}")
        out.append("")

    for good in game.goods_produced:
        rows = recipes_of(game, good, ids)[:RECIPE_ROWS]
        for label in ("bonus", "volume"):
            out.append("wtp_scored_%s_%s = {" % (label, good))
            out.append("\tvalue = 0")
            for index, (name, _) in enumerate(rows):
                keyword = "if" if index == 0 else "else_if"
                out.append("\t%s = { limit = { scope:wtp_scored_recipe = flag:wtp_recipe_%s }"
                           " value = wtp_%s_%s }" % (keyword, name, label, name))
            out.append("}")
        out.append("")
    return "\n".join(out)


def render_menu(game: Game, ids) -> tuple[str, str]:
    """The Mod Menu side: the goods pickers and the recipe rows per good.

    Which row a recipe lands on is fixed by the generator, so both the ordinal and
    the recipe reach the row writer as literals. That is what lets one call set
    the row's label, its tooltip, its value and both of its columns.
    """
    groups = game.goods_by_group()
    out = [BOM + HEADER, "#", "# Scope: country", ""]
    loc = ["l_english:"]

    # Turning a dropdown ordinal back into the good it stands for.
    # Option 1 of every picker is "nothing chosen", so opening the menu does not
    # look like four goods are already selected and one picker can be used on its
    # own. Goods therefore start at ordinal 2.
    for group, _ in CATEGORY_GROUPS:
        out.append("wtp_apply_pick_%s = {" % group)
        for index, good in enumerate(groups[group], start=2):
            keyword = "if" if index == 2 else "else_if"
            out.append("\t%s = { limit = { global_var:wtp_pick_%s = %d }" % (keyword, group, index))
            out.append("\t\tset_global_variable = { name = wtp_good value = goods:%s }" % good)
            out.append("\t}")
        out.append("}")
        out.append("")
        loc.append(' wtp__pick_%s_option_1_name: "$WTP_PICK_NONE$"' % group)
        for index, good in enumerate(groups[group], start=2):
            loc.append(' wtp__pick_%s_option_%d_name: "$%s$"' % (group, index, good))

    out.append("# One row per recipe that makes the chosen good, best output first.")
    out.append("# Scope: country")
    out.append("wtp_fill_recipes = {")
    out.append("\twtp_reset_recipe_rows = yes")
    out.append("")
    for gi, good in enumerate(game.goods_produced):
        keyword = "if" if gi == 0 else "else_if"
        out.append("\t%s = { limit = { global_var:wtp_good = goods:%s }" % (keyword, good))
        rows = recipes_of(game, good, ids)[:RECIPE_ROWS]
        for n, (name, _) in enumerate(rows, start=1):
            out.append("\t\twtp_recipe_row_%d = { m = %s }" % (n, name))
        out.append("\t}")
        for name, method in rows:
            loc += recipe_localization(game, name, method)
    out.append("}")
    out.append("")

    return "\n".join(out), "\n".join(loc) + "\n"


def recipe_localization(game: Game, name: str, method: Method) -> list[str]:
    """The row label and its tooltip, both built out of the game's own names.

    Nothing here is a word in any language: the method, the goods and the two
    captions are all `$key$` references, so one generated file serves every
    localization the mod ships.
    """
    inputs = " + ".join("%s $%s$" % (amount(value), good)
                        for good, value in sorted(method.inputs.items(),
                                                  key=lambda kv: (-kv[1], kv[0])))
    produced = "%s $%s$" % (amount(method.output), method.produced)
    local = ", ".join("$%s$" % good for good in sorted(method.raw_inputs(game.raw_goods)))

    label = "$%s$" % method.key
    if inputs:
        label += " — %s → %s" % (inputs, amount(method.output))

    desc = "$%s$\\n$%s$ %s\\n$%s$ %s\\n$%s$ %s" % (
        method.key, "WTP_IN", inputs or "—", "WTP_OUT", produced, "WTP_FROM_RGO", local)

    return [' wtp_recipe_%s: "%s"' % (name, label),
            ' wtp_recipe_%s_desc: "%s"' % (name, desc)]


def check_cmm_arguments(cmf_effects: Path) -> None:
    """Warn when a cmm_ call uses an argument name CMF does not declare."""
    declared = "".join(p.read_text(encoding="utf-8-sig") for p in cmf_effects.glob("*.txt"))
    ours = "".join(p.read_text(encoding="utf-8-sig")
                   for folder in ("scripted_effects", "scripted_guis")
                   for p in (MOD_ROOT / "in_game" / "common" / folder).glob("*.txt"))
    for call in re.finditer(r"(cmm_[a-z_]+) = \{([^{}]*)\}", ours):
        name, body = call.group(1), call.group(2)
        decl = re.search(r"^%s = \{(.*?)^\}" % re.escape(name), declared, re.S | re.M)
        if decl is None:
            print("unknown CMM effect: %s" % name, file=sys.stderr)
            continue
        allowed = set(re.findall(r"\$(\w+)\$", decl.group(1)))
        extra = set(re.findall(r"^\s*(\w+)\s*=", body, re.M)) - allowed
        if extra:
            print("%s called with %s; CMF declares %s"
                  % (name, sorted(extra), sorted(allowed)), file=sys.stderr)


def check_registration(game: Game, ids) -> None:
    """Warn when the hand written side has drifted from the game data."""
    registration = (MOD_ROOT / "in_game" / "common" / "scripted_effects"
                    / "wtp_registration.txt").read_text(encoding="utf-8-sig")
    effects = (MOD_ROOT / "in_game" / "common" / "scripted_effects"
               / "wtp_effects.txt").read_text(encoding="utf-8-sig")

    for name, rows in game.goods_by_group().items():
        want = len(rows) + 1
        found = re.search(r"setting_id = pick_%s(?:.|\n)*?option_count = (\d+)" % name,
                          registration)
        if found and int(found.group(1)) != want:
            print("option_count for pick_%s is %s, should be %d"
                  % (name, found.group(1), want), file=sys.stderr)

    widest = max((len(recipes_of(game, good, ids)), good) for good in game.goods_produced)
    if widest[0] > RECIPE_ROWS:
        print("%s has %d recipes and the list holds %d; raise RECIPE_ROWS, the "
              "item_count of the recipes list and the row writers to match"
              % (widest[1], widest[0], RECIPE_ROWS), file=sys.stderr)

    found = re.search(r"setting_id = recipes(?:.|\n)*?item_count = (\d+)", registration)
    if found and int(found.group(1)) != RECIPE_ROWS:
        print("item_count for the recipes list is %s, should be %d"
              % (found.group(1), RECIPE_ROWS), file=sys.stderr)

    for n in range(1, RECIPE_ROWS + 1):
        if "wtp_recipe_row_%d = {" % n not in effects:
            print("wtp_effects.txt has no wtp_recipe_row_%d; the generator emits "
                  "calls up to %d" % (n, RECIPE_ROWS), file=sys.stderr)


def main() -> int:
    if len(sys.argv) not in (2, 3):
        print(__doc__)
        return 2
    common = Path(sys.argv[1])
    missing = [n for n in ("goods", "production_methods", "building_types")
               if not (common / n).is_dir()]
    if missing:
        print("missing under %s: %s" % (common, ", ".join(missing)), file=sys.stderr)
        return 1

    game = load_game(common)
    ids = resolve_ids(game)

    used_goods = sorted({
        good
        for m in game.methods
        for good in m.raw_inputs(game.raw_goods)
    })

    menu, menu_loc = render_menu(game, ids)

    for path, text in ((TRIGGERS_OUT, render_triggers(used_goods)),
                       (VALUES_OUT, render_values(game, ids)),
                       (SCORING_OUT, render_scoring(game, ids)),
                       (MENU_OUT, menu),
                       ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    for path in RETIRED:
        if path.exists():
            path.unlink()
            print("removed %s" % path.relative_to(MOD_ROOT.parent))

    scored = {ids[(m.building, m.key)] for m in game.methods if m.raw_inputs(game.raw_goods)}
    # A macro called with an argument CMF does not declare fails silently at
    # load and takes the rest of its effect with it -- which is how one `step`
    # instead of `step_value` emptied both lists.
    if len(sys.argv) > 2:
        check_cmm_arguments(Path(sys.argv[2]))
    check_registration(game, ids)

    print("goods per picker:         %s" % {n: len(r) + 1
                                            for n, r in game.goods_by_group().items()})
    print("raw materials referenced: %d" % len(used_goods))
    print("methods scored:           %d" % len(scored))
    print("goods reachable:          %d" % len(game.goods_produced))
    print("widest good:              %d recipes" % max(
        len(recipes_of(game, good, ids)) for good in game.goods_produced))

    for language in LOC_LANGUAGES:
        path = MOD_ROOT / "main_menu" / "localization" / language / ("wtp_generated_l_%s.yml" % language)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("﻿" + menu_loc.replace("l_english:", "l_%s:" % language, 1),
                        encoding="utf-8")

    for path in (TRIGGERS_OUT, VALUES_OUT, SCORING_OUT, MENU_OUT):
        print("wrote %s" % path.relative_to(MOD_ROOT.parent))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
